calmato/shs-web

- api/internal/user/api/teacher.go
- api/internal/user/api/teacher_test.go
- api/internal/user/database/database.go
- api/internal/user/database/teacher.go
- api/internal/user/database/teacher_test.go
- api/internal/user/entity/teacher.go
- api/internal/user/entity/teacher_test.go
- api/internal/user/validation/teacher.go
- api/internal/user/validation/teacher_test.go
- api/internal/user/validation/validator.go
- api/mock/proto/user/service_grpc.pb.go.go
- api/mock/user/database/database.go
- api/mock/user/validation/validator.go
- api/proto/user/service.proto
講師一覧取得APIの実装
デザインが確定していないため、リクエスト値については未FIX
> feat(user-api): implement list teachers api

- docs/swagger/teacher/components/schemas/v1/auth.response.yaml
- docs/swagger/teacher/components/schemas/v1/teachers.request.yaml
- docs/swagger/teacher/components/schemas/v1/teachers.response.yaml
- docs/swagger/teacher/components/schemas/v1/user.request.yaml
- docs/swagger/teacher/components/schemas/v1/user.response.yaml
- docs/swagger/teacher/openapi.yaml
- docs/swagger/teacher/paths/v1/auth.index.yaml
- docs/swagger/teacher/paths/v1/teachers.id.yaml
- docs/swagger/teacher/paths/v1/teachers.index.yaml
> docs(swagger): update teacher api docs

- .github/reviewer.yaml
> chore(*): add pr reviewers

- Makefile
> feat(infra): update docker-compose

- api/internal/user/api/teacher.go
- api/internal/user/api/teacher_test.go
- api/internal/user/database/database.go
- api/internal/user/database/teacher.go
- api/internal/user/database/teacher_test.go
- api/internal/user/validation/teacher.go
- api/internal/user/validation/teacher_test.go
- api/internal/user/validation/validator.go
- api/mock/proto/user/service_grpc.pb.go.go
- api/mock/user/database/database.go
- api/mock/user/validation/validator.go
- api/pkg/database/client.go
- api/pkg/database/client_test.go
- api/pkg/jst/jst.go
- api/proto/user/service.proto
> feat(user-api): implement get teacher api

- Makefile
- vetur.config.js
- Makeのタスクに`ps`を追加した。
- プロジェクトルートに`vetur.config.js`を追加
参考までに
https://vuejs.github.io/vetur/reference/#example
これに関してはなし。
ないです。
> VSCodeの開発環境向けのファイルを用意

- api/internal/gateway/teacher/v1/handler/api.go
- api/internal/gateway/teacher/v1/handler/auth.go
- api/internal/gateway/teacher/v1/handler/auth_test.go
- api/internal/gateway/teacher/v1/handler/teacher.go
- api/internal/gateway/teacher/v1/handler/teacher_test.go
> feat(gateway): implement get teacher api

- api/internal/gateway/entity/teacher.go
- api/internal/gateway/entity/teacher_test.go
- api/internal/gateway/teacher/v1/entity/teacher.go
- api/internal/gateway/teacher/v1/entity/teacher_test.go
- api/internal/gateway/teacher/v1/handler/api.go
- api/internal/gateway/teacher/v1/handler/teacher.go
- api/internal/gateway/teacher/v1/handler/teacher_test.go
> feat(gateway): implement create teacher api

- docs/swagger/teacher/openapi.yaml
> docs(swagger): fix get auth api path

- api/internal/gateway/cmd/teacher/router.go
- api/internal/gateway/teacher/v1/handler/api.go
管理者のみアクセスが可能なエンドポイントに対して認可処理を行うように設定
> fix(gateway): fix authorization middleware

- infra/mysql/schema/2021121102-users-alter-table-students.sql
studentsテーブルにprimary keyを追加
students用のapi作成
> fix: add PRYMARY KEY

- infra/mysql/schema/2021121102-users-alter-table-students.sql
typoでMySQLコンテナがうまく動作していないバグを修正
> fix(mysql): fix typo

- api/internal/gateway/entity/teacher.go
- api/internal/gateway/entity/teacher_test.go
- api/internal/gateway/teacher/v1/entity/teacher.go
- api/internal/gateway/teacher/v1/entity/teacher_test.go
- api/internal/gateway/teacher/v1/handler/api.go
- api/internal/gateway/teacher/v1/handler/teacher.go
- api/internal/gateway/teacher/v1/handler/teacher_test.go
- api/internal/gateway/teacher/v1/response/teacher.go
> feat(gateway): implement list teachers api

- api/Makefile
- api/config/gateway/teacher/config.go
- api/config/user/server/config.go
- api/internal/gateway/cmd/teacher/exec.go
- api/internal/gateway/cmd/teacher/registry.go
- api/internal/gateway/teacher/v1/handler/api.go
- api/internal/user/cmd/server/exec.go
- docker-compose.yaml
* Firebase Authenticationのクライアントがうまく参照できなかったため修正
* ビルド時に生成されるファイル名が同一でロックが掛かりうまく動作していなかったため別名生成に修正
* DockerCompose周りの環境設定を改善
> fix(*): fix dependency injection in gateway

- .codecov.yaml
- .github/workflows/ci-backend-for-all.yaml
> fix(workflow): fix coverage flags

- Makefile
- api/hack/database-seeds/main.go
- bin/database-migrate.sh
> feat(infra): setup database migrate command

- web/teacher/src/components/templates/MbShiftTop.vue
- web/teacher/src/components/templates/PcShiftTop.vue
- web/teacher/src/components/templates/TheSettingTop.vue
- web/teacher/src/components/templates/TheSignIn.vue
- web/teacher/src/components/templates/TheTop.vue
- web/teacher/src/components/templates/TheUserTop.vue
> feat(web/teacher): adjust layout

- web/teacher/src/components/organisms/TheTeacherList.vue
- web/teacher/src/components/templates/TheUserTop.vue
- web/teacher/src/pages/users/index.vue
- web/teacher/src/store/user.ts
- web/teacher/src/types/api/v1/user.ts
- web/teacher/src/types/props/user.ts
- web/teacher/src/types/store/user.ts
- web/teacher/test/components/organisms/TheTeacherList.test.ts
- web/teacher/test/components/templates/TheUserTop.test.ts
- web/teacher/test/helpers/api-mock/user.ts
- web/teacher/test/store/user.test.ts
> feat(web/teacher): update list teachers page

- web/teacher/src/components/templates/TheSignIn.vue
> fix(web/teacher): fix field type

- web/teacher/nuxt.config.js
- web/teacher/package.json
- web/teacher/src/components/atoms/TheFormGroup.vue
- web/teacher/src/components/atoms/TheSelect.vue
- web/teacher/src/components/atoms/TheTextField.vue
- web/teacher/src/components/organisms/TheTeacherNewForm.vue
- web/teacher/src/components/templates/TheTeacherNew.vue
- web/teacher/src/pages/users/teachers/new.vue
- web/teacher/src/plugins/vee-validate.ts
- web/teacher/src/store/user.ts
- web/teacher/src/types/api/v1/user.ts
- web/teacher/src/types/form/index.ts
- web/teacher/src/types/form/teacher.ts
- web/teacher/src/types/form/util.ts
- web/teacher/src/types/props/teacher.ts
- web/teacher/test/components/atoms/TheFormGroup.test.ts
- web/teacher/test/components/atoms/TheSelect.test.ts
- web/teacher/test/components/atoms/TheTextField.test.ts
- web/teacher/test/components/organisms/TheTeacherNewForm.test.ts
- web/teacher/test/components/templates/TheTeacherNew.test.ts
- web/teacher/test/helpers/api-mock/index.ts
- web/teacher/test/helpers/api-mock/user.ts
- web/teacher/test/helpers/setup.ts
- web/teacher/test/helpers/store-helper.ts
- web/teacher/test/store/user.test.ts
- web/teacher/tsconfig.json
- web/teacher/yarn.lock
> feat(web/teacher): implement create teacher page

- web/teacher/src/pages/index.vue
講師周りの実装の関係でトップページのMockがうまく動かなくなったので修正しました
> fix(web/teacher): fix lesson mock

- web/teacher/src/pages/settings/index.vue
- web/teacher/src/store/auth.ts
- web/teacher/src/store/user.ts
- web/teacher/test/store/auth.test.ts
> feat(web/teacher): implament signout

- api/internal/user/database/teacher.go
countクエリでは `deleted_at IS NULL` 判定が含まれていないため、明示的に絞り込みするよう修正しました。
> fix(user-api): fix count query

- api/internal/classroom/api/subject.go
- api/internal/classroom/api/subject_test.go
- api/internal/classroom/database/database.go
- api/internal/classroom/database/subject.go
- api/internal/classroom/database/subject_test.go
- api/internal/classroom/validation/subject.go
- api/internal/classroom/validation/subject_test.go
- api/internal/classroom/validation/validator.go
- api/internal/user/api/teacher_test.go
- api/internal/user/database/teacher_test.go
- api/internal/user/validation/teacher_test.go
- api/mock/classroom/database/database.go
- api/mock/classroom/validation/validator.go
> feat(classroom-api): implement get subject api

- bin/database-migrate.sh
* コンテナがすでに作成されている場合は再作成されるように設定
> chore(*): update database script

- api/internal/user/api/api_test.go
- api/internal/user/database/database.go
- api/internal/user/database/student.go
- api/mock/user/database/database.go
このあと @sea-kai に実装を進めてもらうために、Student周りのInterface作成をしました
> feat(user-api): setup student interface

- api/internal/classroom/api/subject.go
- api/internal/classroom/api/subject_test.go
- api/internal/classroom/database/database.go
- api/internal/classroom/database/subject.go
- api/internal/classroom/database/subject_test.go
- api/internal/classroom/validation/subject_test.go
- api/mock/classroom/database/database.go
- api/proto/classroom/service.proto
教科一覧取得については全件取得したいはずなので、limit, offset指定をなくしました
> fix(classroom-api): fix list subjects api

- api/config/gateway/teacher/config.go
- api/internal/gateway/cmd/teacher/exec.go
- api/internal/gateway/cmd/teacher/registry.go
- api/internal/gateway/entity/subject.go
- api/internal/gateway/entity/subject_test.go
- api/internal/gateway/teacher/v1/entity/subject.go
- api/internal/gateway/teacher/v1/entity/subject_test.go
- api/internal/gateway/teacher/v1/handler/api.go
- api/internal/gateway/teacher/v1/handler/api_test.go
- api/internal/gateway/teacher/v1/handler/subject.go
- api/internal/gateway/teacher/v1/handler/subject_test.go
- api/internal/gateway/teacher/v1/response/subject.go
- api/mock/user/database/database.go
- docker-compose.yaml
- docs/swagger/teacher/components/schemas/v1/subjects.response.yaml
- docs/swagger/teacher/openapi.yaml
- docs/swagger/teacher/paths/v1/subjects.index.yaml
> feat(gateway): implement list subjects api

- api/internal/gateway/entity/student.go
- api/internal/gateway/entity/student_test.go
> feat(user-api):add student entity

- api/internal/gateway/teacher/v1/entity/subject.go
- api/internal/gateway/teacher/v1/handler/api.go
- api/internal/gateway/teacher/v1/handler/auth.go
- api/internal/gateway/teacher/v1/handler/auth_test.go
- api/internal/gateway/teacher/v1/handler/subject.go
- api/internal/gateway/teacher/v1/handler/teacher_test.go
- api/internal/gateway/teacher/v1/request/auth.go
- docs/swagger/teacher/components/schemas/v1/auth.request.yaml
- docs/swagger/teacher/openapi.yaml
- docs/swagger/teacher/paths/v1/me/index.yaml
- docs/swagger/teacher/paths/v1/me/subjects.yaml
- docs/swagger/teacher/paths/v1/subjects/index.yaml
- docs/swagger/teacher/paths/v1/teachers/_id.yaml
- docs/swagger/teacher/paths/v1/teachers/index.yaml
> feat(gateway): add update my subjects api mock

- infra/mysql/schema/2021120902-users-create-table-teachers.sql
- infra/mysql/schema/2021120903-users-create-table-students.sql
- infra/mysql/schema/2021121101-users-alter-table-teachers.sql
- infra/mysql/schema/2021121102-users-alter-table-students.sql
- infra/mysql/schema/2021121801-classrooms-create-table-subjects.sql
- infra/mysql/schema/2021121901-classrooms-add-column-to-subjects.sql
- infra/mysql/schema/2021122101-classrooms-create-table-subjects-teachers.sql
> refactor(mysql): refactor mysql schemas

- web/teacher/src/components/templates/TheSignIn.vue
- web/teacher/test/components/templates/TheSignIn.test.ts
ログインフォームの送信をEnterキーでできるようにした
特になし
特になし
> feat: ログインをEnterキーでできるようにした

- api/internal/classroom/api/api_test.go
- api/internal/classroom/api/teacher_subject.go
- api/internal/classroom/api/teacher_subject_test.go
- api/internal/classroom/database/database.go
- api/internal/classroom/database/teacher_subject.go
- api/internal/classroom/database/teacher_subject_test.go
- api/internal/classroom/entity/teacher_subject.go
- api/internal/classroom/entity/teacher_subject_test.go
- api/internal/classroom/validation/teacher_subject.go
- api/internal/classroom/validation/teacher_subject_test.go
- api/internal/classroom/validation/validator.go
- api/mock/classroom/database/database.go
- api/mock/classroom/validation/validator.go
- api/mock/proto/classroom/service_grpc.pb.go.go
- api/pkg/set/set.go
- api/pkg/set/set_test.go
- api/proto/classroom/service.proto
- api/proto/classroom/teacher_subject.proto
- infra/mysql/schema/2021122102-classrooms-alter-table-teacher-subjects.sql
> feat(classroom-api): implement get teacher subject api

- Makefile
- api/internal/classroom/api/teacher_subject_test.go
- api/internal/classroom/entity/teacher_subject_test.go
- api/internal/gateway/entity/teacher_subject.go
- api/internal/gateway/entity/teacher_subject_test.go
- api/internal/gateway/teacher/v1/entity/subject.go
- api/internal/gateway/teacher/v1/entity/subject_test.go
- api/internal/gateway/teacher/v1/handler/auth.go
- api/internal/gateway/teacher/v1/handler/auth_test.go
- api/internal/gateway/teacher/v1/handler/subject.go
- api/internal/gateway/teacher/v1/response/auth.go
- docs/swagger/teacher/components/schemas/v1/auth.response.yaml
> feat(gateway): update get auth api

- api/internal/gateway/teacher/v1/handler/auth.go
- api/internal/gateway/teacher/v1/handler/auth_test.go
- api/internal/gateway/teacher/v1/handler/subject.go
- docs/swagger/teacher/paths/v1/me/subjects.yaml
> feat(gateway): implement update my subjects

- api/internal/classroom/api/teacher_subject.go
- api/internal/classroom/api/teacher_subject_test.go
- api/internal/gateway/teacher/v1/handler/auth_test.go
- api/proto/classroom/service.proto
Update処理のときはResponseを空で返すように修正しました
> refactor(classroom-api): remove update api response

- api/internal/gateway/teacher/v1/handler/subject.go
- api/internal/gateway/teacher/v1/handler/subject_test.go
- docs/swagger/teacher/paths/v1/me/index.yaml
- docs/swagger/teacher/paths/v1/subjects/index.yaml
- docs/swagger/teacher/paths/v1/teachers/_id.yaml
- docs/swagger/teacher/paths/v1/teachers/index.yaml
> feat(gateway): add query path in list subjects api

- infra/functions/gcr-cleaner/go.mod
- infra/functions/gcr-cleaner/go.sum
dependabotのアラート対応
* https://github.com/calmato/shs-web/security/dependabot/infra/functions/gcr-cleaner/go.sum/github.com%2Fopencontainers%2Fimage-spec/open
> chore(functions): update deps

- api/internal/classroom/api/schedule.go
- api/internal/classroom/api/schedule_test.go
- api/internal/classroom/database/database.go
- api/internal/classroom/database/schedule.go
- api/internal/classroom/database/schedule_test.go
- api/internal/classroom/entity/schedule.go
- api/internal/classroom/entity/schedule_test.go
- api/internal/classroom/validation/schedule.go
- api/internal/classroom/validation/schedule_test.go
- api/internal/classroom/validation/validator.go
- api/mock/classroom/database/database.go
- api/mock/classroom/validation/validator.go
- api/mock/proto/classroom/service_grpc.pb.go.go
- api/proto/classroom/service.proto
> feat(classroom-api): implement update schedules api

- api/internal/gateway/entity/schedule.go
- api/internal/gateway/entity/schedule_test.go
- api/internal/gateway/teacher/v1/entity/schedule.go
- api/internal/gateway/teacher/v1/entity/schedule_test.go
- api/internal/gateway/teacher/v1/handler/api.go
- api/internal/gateway/teacher/v1/handler/schedule.go
- api/internal/gateway/teacher/v1/handler/schedule_test.go
- api/internal/gateway/teacher/v1/request/auth.go
- api/internal/gateway/teacher/v1/request/schedule.go
- api/internal/gateway/teacher/v1/request/teacher.go
- api/internal/gateway/teacher/v1/response/auth.go
- api/internal/gateway/teacher/v1/response/schedule.go
- docs/swagger/teacher/components/schemas/v1/auth.request.yaml
- docs/swagger/teacher/components/schemas/v1/auth.response.yaml
- docs/swagger/teacher/components/schemas/v1/schedules.request.yaml
- docs/swagger/teacher/components/schemas/v1/schedules.response.yaml
- docs/swagger/teacher/components/schemas/v1/subjects.response.yaml
- docs/swagger/teacher/components/schemas/v1/teachers.request.yaml
- docs/swagger/teacher/components/schemas/v1/teachers.response.yaml
- docs/swagger/teacher/openapi.yaml
- docs/swagger/teacher/paths/v1/schedules/index.yaml
> feat(gateway): implement schedule api

- api/internal/classroom/api/subject.go
- api/internal/classroom/api/subject_test.go
- api/internal/classroom/database/database.go
- api/internal/classroom/database/subject.go
- api/internal/classroom/database/subject_test.go
- api/internal/classroom/entity/subject.go
- api/internal/classroom/entity/subject_test.go
- api/internal/classroom/validation/subject.go
- api/internal/classroom/validation/subject_test.go
- api/internal/classroom/validation/validator.go
- api/mock/classroom/database/database.go
- api/mock/classroom/validation/validator.go
- api/mock/proto/classroom/service_grpc.pb.go.go
- api/proto/classroom/service.proto
> feat(classroom-api): implement subject api

- api/internal/classroom/entity/subject.go
- api/internal/classroom/entity/subject_test.go
カラーコードをアッパーケースに修正する処理をマイクロサービス側に寄せました
> refactor(classroom-api): refactor upper case to color code

- api/internal/gateway/teacher/v1/entity/subject.go
- api/internal/gateway/teacher/v1/entity/subject_test.go
- api/internal/gateway/teacher/v1/handler/api.go
- api/internal/gateway/teacher/v1/handler/auth_test.go
- api/internal/gateway/teacher/v1/handler/subject.go
- api/internal/gateway/teacher/v1/handler/subject_test.go
- api/internal/gateway/teacher/v1/request/subject.go
- api/internal/gateway/teacher/v1/response/subject.go
- docs/swagger/teacher/components/schemas/v1/subjects.request.yaml
- docs/swagger/teacher/components/schemas/v1/subjects.response.yaml
- docs/swagger/teacher/openapi.yaml
- docs/swagger/teacher/paths/v1/subjects/_id.yaml
> feat(gateway): implement subject api

- infra/docker/api/classroom/server/Dockerfile.development
- infra/docker/api/gateway/teacher/Dockerfile.development
- infra/docker/api/lesson/server/Dockerfile.development
- infra/docker/api/user/server/Dockerfile.development
- infra/docker/web/teacher/Dockerfile.development
> feat(infra): update api container image for dev

- web/teacher/yarn.lock
`yarn.lock`の再生成でセキュリティアラートに対応できるかを確認するために消して作り直した。
> chore: yarn.lockを再生成

- api/internal/gateway/teacher/v1/handler/api.go
- api/internal/gateway/teacher/v1/handler/subject_test.go
- api/internal/gateway/teacher/v1/handler/teacher.go
- api/internal/gateway/teacher/v1/handler/teacher_test.go
- api/internal/gateway/teacher/v1/request/teacher.go
- docs/swagger/openapitools.json
- docs/swagger/teacher/components/schemas/v1/teachers.request.yaml
- docs/swagger/teacher/openapi.yaml
- docs/swagger/teacher/paths/v1/subjects/_subjectId.yaml
- docs/swagger/teacher/paths/v1/teachers/_teacherId/index.yaml
- docs/swagger/teacher/paths/v1/teachers/_teacherId/mail.yaml
- docs/swagger/teacher/paths/v1/teachers/_teacherId/password.yaml
- docs/swagger/yarn.lock
> feat(gateway): implement update teacher email and password api

- api/hack/database-seeds/main.go
データベースへ開発用データを追加するためのコマンドを更新しました
* ローカルでの実行
> $ docker-compose start mysql
> $ cd api/hack/database-seeds; go run ./main.go -db-host=127.0.0.1 -db-port=3316 -db-password=12345678; cd -
* コンテナでの実行
> $ make migrate
> feat(hack): update database seeds command

- docs/swagger/teacher/paths/v1/subjects/_subjectId.yaml
> fix(docs): typo

- api/hack/database-seeds/main.go
- api/internal/classroom/api/api_test.go
- api/internal/classroom/api/room.go
- api/internal/classroom/api/room_test.go
- api/internal/classroom/database/database.go
- api/internal/classroom/database/room.go
- api/internal/classroom/database/room_test.go
- api/internal/classroom/entity/room.go
- api/internal/classroom/entity/room_test.go
- api/internal/classroom/validation/room.go
- api/internal/classroom/validation/room_test.go
- api/internal/classroom/validation/validator.go
- api/mock/classroom/database/database.go
- api/mock/classroom/validation/validator.go
- api/mock/proto/classroom/service_grpc.pb.go.go
- api/proto/classroom/service.proto
> feat(classroom-api): implement rooms api

- api/internal/gateway/teacher/v1/handler/api.go
- api/internal/gateway/teacher/v1/handler/room.go
- api/internal/gateway/teacher/v1/handler/room_test.go
- api/internal/gateway/teacher/v1/request/room.go
- api/internal/gateway/teacher/v1/response/room.go
- docs/swagger/teacher/components/schemas/v1/rooms.request.yaml
- docs/swagger/teacher/components/schemas/v1/rooms.response.yaml
- docs/swagger/teacher/openapi.yaml
- docs/swagger/teacher/paths/v1/rooms/index.yaml
> feat(gateway): implement rooms total api

- api/internal/lesson/entity/shift.go
- api/internal/lesson/entity/shift_summary.go
- api/internal/lesson/entity/shift_summary_test.go
- api/internal/lesson/entity/shift_test.go
- api/pkg/jst/jst.go
- api/pkg/jst/jst_test.go
- api/proto/lesson/common.proto
- api/proto/lesson/shift.proto
- api/proto/lesson/shift_summary.proto
- infra/mysql/schema/2021122702-lessons-create-table-shifts.sql
> feat(lesson-api): define shift entity

- api/config/lesson/server/config.go
- api/internal/lesson/api/api.go
- api/internal/lesson/api/api_test.go
- api/internal/lesson/api/shift.go
- api/internal/lesson/api/shift_test.go
- api/internal/lesson/cmd/server/exec.go
- api/internal/lesson/cmd/server/registry.go
- api/internal/lesson/database/database.go
- api/internal/lesson/database/database_test.go
- api/internal/lesson/database/shift.go
- api/internal/lesson/database/shift_summary.go
- api/internal/lesson/database/shift_summary_test.go
- api/internal/lesson/database/shift_test.go
- api/internal/lesson/entity/schedule.go
- api/internal/lesson/entity/schedule_test.go
- api/internal/lesson/entity/shift.go
- api/internal/lesson/entity/shift_summary.go
- api/internal/lesson/entity/shift_summary_test.go
- api/internal/lesson/entity/shift_test.go
- api/internal/lesson/validation/shift.go
- api/internal/lesson/validation/shift_test.go
- api/internal/lesson/validation/validator.go
- api/mock/lesson/database/database.go
- api/mock/lesson/validation/validator.go
- api/mock/proto/lesson/service_grpc.pb.go.go
- api/proto/lesson/service.proto
- docker-compose.yaml
> feat(lesson-api): implement create shits api

- api/internal/gateway/entity/shift.go
- api/internal/gateway/entity/shift_summary.go
- api/internal/gateway/entity/shift_summary_test.go
- api/internal/gateway/entity/shift_test.go
- api/internal/gateway/teacher/v1/entity/shift.go
- api/internal/gateway/teacher/v1/entity/shift_summary.go
- api/internal/gateway/teacher/v1/entity/shift_summary_test.go
- api/internal/gateway/teacher/v1/entity/shift_test.go
- api/internal/gateway/teacher/v1/handler/api.go
- api/internal/gateway/teacher/v1/handler/shift.go
- api/internal/gateway/teacher/v1/handler/shift_test.go
- api/internal/gateway/teacher/v1/request/shift.go
- api/internal/gateway/teacher/v1/response/shift.go
- docs/swagger/teacher/components/schemas/v1/shifts.request.yaml
- docs/swagger/teacher/components/schemas/v1/shifts.response.yaml
- docs/swagger/teacher/openapi.yaml
- docs/swagger/teacher/paths/v1/shifts/index.yaml
> feat(gateway): implement create shifts api

- api/internal/user/api/api_test.go
- api/internal/user/api/student.go
- api/internal/user/api/student_test.go
- api/internal/user/validation/student.go
- api/internal/user/validation/student_test.go
- api/internal/user/validation/validator.go
- api/mock/user/validation/validator.go
> feat(user-api): GetStudent usecase

- api/internal/gateway/teacher/v1/entity/shift.go
- api/internal/gateway/teacher/v1/entity/shift_test.go
- api/internal/gateway/teacher/v1/handler/shift.go
- api/internal/gateway/teacher/v1/handler/shift_test.go
- api/internal/gateway/teacher/v1/response/shift.go
- docs/swagger/teacher/components/schemas/v1/shifts.response.yaml
募集シフトで返すレスポンスについて、休校であるかの判別用のフラグを追加しました
> feat(gateway): changing create shifts response

- web/teacher/src/components/templates/TheSubmission.vue
- web/teacher/src/layouts/default.vue
- web/teacher/src/pages/submissions/index.vue
- web/teacher/src/plugins/store-accessor.ts
- web/teacher/src/store/submission.ts
- web/teacher/src/types/props/submission.ts
- web/teacher/src/types/store/submission.ts
授業希望ページの作成
とりあえず、コンポーネントで分けないで実装しました。のちに分ける予定。
> Add: added submission page

- api/mock/proto/user/service_grpc.pb.go.go
- api/proto/user/service.proto
- api/proto/user/student.proto
service.protoにCreateStudentのrequestとresponseを作成
このファイルには受け取りたい形を書くってことであってますよね？
> add request and response proto

- api/internal/gateway/teacher/v1/entity/shift_summary.go
- api/internal/gateway/teacher/v1/entity/shift_summary_test.go
- api/internal/gateway/teacher/v1/handler/api.go
- api/internal/gateway/teacher/v1/handler/shift.go
- api/internal/gateway/teacher/v1/handler/shift_test.go
- api/internal/gateway/teacher/v1/response/shift.go
- docs/swagger/teacher/components/schemas/v1/shifts.response.yaml
- docs/swagger/teacher/openapi.yaml
- docs/swagger/teacher/paths/v1/shifts/index.yaml
> feat(gateway): implement list shift summaries api

- api/internal/lesson/api/shift.go
- api/internal/lesson/api/shift_test.go
- api/internal/lesson/database/database.go
- api/internal/lesson/database/shift.go
- api/internal/lesson/database/shift_test.go
- api/internal/lesson/validation/shift.go
- api/internal/lesson/validation/shift_test.go
- api/internal/lesson/validation/validator.go
- api/mock/lesson/database/database.go
- api/mock/lesson/validation/validator.go
- api/mock/proto/lesson/service_grpc.pb.go.go
- api/proto/lesson/service.proto
> feat(lesson-api): implement list shifts api

- api/internal/lesson/api/shift.go
- api/internal/lesson/api/shift_test.go
- api/internal/lesson/database/database.go
- api/internal/lesson/database/shift_summary.go
- api/internal/lesson/database/shift_summary_test.go
- api/internal/lesson/validation/shift.go
- api/internal/lesson/validation/shift_test.go
- api/internal/lesson/validation/validator.go
- api/mock/lesson/database/database.go
- api/mock/lesson/validation/validator.go
- api/mock/proto/lesson/service_grpc.pb.go.go
- api/proto/lesson/service.proto
> feat(lesson-api): implement get shift summary api

- api/internal/gateway/teacher/v1/handler/api.go
- api/internal/gateway/teacher/v1/handler/shift.go
- api/internal/gateway/teacher/v1/handler/shift_test.go
- docs/swagger/teacher/openapi.yaml
- docs/swagger/teacher/paths/v1/shifts/_shiftId.yaml
> feat(gateway): implement list shifts api

- web/teacher/src/components/organisms/TheShiftTopCard.vue
- web/teacher/src/components/templates/PcShiftTop.vue
- web/teacher/src/pages/shifts/index.vue
- web/teacher/src/plugins/store-accessor.ts
- web/teacher/src/store/shift.ts
- web/teacher/src/types/api/v1/index.ts
- web/teacher/src/types/api/v1/shift.ts
- web/teacher/src/types/store/common.ts
- web/teacher/src/types/store/index.ts
- web/teacher/src/types/store/shift.ts
- web/teacher/test/components/organisms/TheShiftTopCard.test.ts
- web/teacher/test/components/templates/PcShiftTop.test.ts
- web/teacher/test/helpers/api-mock/index.ts
- web/teacher/test/helpers/api-mock/shift.ts
- web/teacher/test/helpers/store-helper.ts
- web/teacher/test/store/shift.test.ts
> feat(web/teacher): implement shift top page when use desktop

- web/teacher/src/components/atoms/TheSelect.vue
- web/teacher/src/components/atoms/TheTextField.vue
- web/teacher/src/components/molecules/TheDatePicker.vue
- web/teacher/src/components/organisms/TheShiftNewCard.vue
- web/teacher/src/components/templates/PcShiftTop.vue
- web/teacher/src/pages/shifts/index.vue
- web/teacher/src/plugins/vee-validate.ts
- web/teacher/src/store/shift.ts
- web/teacher/src/types/api/v1/shift.ts
- web/teacher/src/types/form/index.ts
- web/teacher/src/types/form/shift.ts
- web/teacher/src/types/form/util.ts
- web/teacher/src/types/store/shift.ts
- web/teacher/test/components/molecules/TheDatePicker.test.ts
- web/teacher/test/components/organisms/TheShiftNewCard.test.ts
- web/teacher/test/components/templates/PcShiftTop.test.ts
- web/teacher/test/helpers/api-mock/index.ts
- web/teacher/test/helpers/api-mock/shift.ts
- web/teacher/test/store/shift.test.ts
> feat(web/teacher): implement create shifts dialog

- api/internal/classroom/database/database_test.go
- api/internal/lesson/database/database_test.go
- api/internal/user/database/database_test.go
> test(api): add test code

- api/internal/lesson/api/shift.go
- api/internal/lesson/api/shift_test.go
- api/internal/lesson/database/database.go
- api/internal/lesson/database/shift_summary.go
- api/internal/lesson/database/shift_summary_test.go
- api/internal/lesson/validation/shift.go
- api/internal/lesson/validation/shift_test.go
- api/internal/lesson/validation/validator.go
- api/mock/lesson/database/database.go
- api/mock/lesson/validation/validator.go
- api/mock/proto/lesson/service_grpc.pb.go.go
- api/proto/lesson/service.proto
> feat(lesson-api): implement delete shift summary

- web/teacher/src/store/shift.ts
- web/teacher/src/types/api/v1/shift.ts
- web/teacher/src/types/store/shift.ts
- web/teacher/test/helpers/api-mock/shift.ts
- web/teacher/test/store/shift.test.ts
https://github.com/calmato/shs-web/pull/116 の修正に合わせてフロントエンドも修正
> fix(web/teacher): fix shifts response

- web/teacher/src/components/organisms/TheShiftEditCard.vue
- web/teacher/src/components/templates/PcShiftTop.vue
- web/teacher/src/pages/shifts/index.vue
- web/teacher/src/store/shift.ts
- web/teacher/src/types/api/v1/shift.ts
- web/teacher/src/types/form/shift.ts
- web/teacher/src/types/form/util.ts
- web/teacher/test/components/organisms/TheShiftEditCard.test.ts
- web/teacher/test/components/templates/PcShiftTop.test.ts
- web/teacher/test/helpers/api-mock/index.ts
- web/teacher/test/helpers/api-mock/shift.ts
- web/teacher/test/helpers/store-helper.ts
- web/teacher/test/store/shift.test.ts
> feat(web/teacher): implement shift update dialog

- api/internal/gateway/teacher/v1/handler/api.go
- api/internal/gateway/teacher/v1/handler/shift.go
- api/internal/gateway/teacher/v1/handler/shift_test.go
- api/internal/gateway/teacher/v1/request/shift.go
- docs/swagger/teacher/components/schemas/v1/shifts.request.yaml
- docs/swagger/teacher/openapi.yaml
- docs/swagger/teacher/paths/v1/shifts/_shiftId/index.yaml
- docs/swagger/teacher/paths/v1/shifts/_shiftId/schedule.yaml
> feat(gateway): implement update shift summary api

- web/teacher/src/pages/shifts/index.vue
- web/teacher/src/store/shift.ts
シフトの募集期間の修正, シフト募集の削除APIとの連携を行いました
> feat(web/teacher): implement update shifts

- docs/swagger/teacher/openapi.yaml
ルーム関連APIのドキュメントの記載が抜けていたため、追記しました
> docs(swagger): add rooms api

- api/internal/classroom/api/teacher_subject.go
- api/internal/classroom/api/teacher_subject_test.go
- api/internal/classroom/database/teacher_subject.go
- api/internal/classroom/database/teacher_subject_test.go
- api/internal/classroom/validation/teacher_subject.go
- api/internal/classroom/validation/teacher_subject_test.go
- api/internal/classroom/validation/validator.go
- api/internal/gateway/teacher/v1/handler/auth.go
- api/internal/gateway/teacher/v1/handler/auth_test.go
- api/mock/classroom/validation/validator.go
- api/mock/proto/classroom/service_grpc.pb.go.go
- api/proto/classroom/service.proto
担当教科を0にしたいときInternalエラーが返るため修正しました
> fix(*): fix upsert teacher subject

- api/internal/gateway/teacher/v1/handler/shift.go
- api/internal/gateway/teacher/v1/handler/shift_test.go
- api/pkg/jst/jst.go
- api/pkg/jst/jst_test.go
* typoの修正
* https://github.com/jinzhu/now/blob/master/now.go を参考に `EndOfDay` メソッドの追加
> fix(api): fix jst package

- api/internal/classroom/api/api.go
- api/internal/classroom/api/api_test.go
- api/internal/classroom/api/teacher_subject.go
- api/internal/classroom/api/teacher_subject_test.go
> fix(classroom-api): fix upsert teacher subject

- api/internal/lesson/api/teacher_shift.go
- api/internal/lesson/api/teacher_shift_test.go
- api/internal/lesson/entity/teacher_submission.go
- api/internal/lesson/entity/teacher_submission_test.go
- api/proto/lesson/common.proto
- api/proto/lesson/teacher_submission.proto
> fix(lesson-api): remove status

- api/internal/lesson/api/api_test.go
- api/internal/lesson/api/teacher_shift.go
- api/internal/lesson/api/teacher_shift_test.go
- api/internal/lesson/database/database.go
- api/internal/lesson/database/teacher_submission.go
- api/internal/lesson/database/teacher_submission_test.go
- api/internal/lesson/entity/teacher_submission.go
- api/internal/lesson/entity/teacher_submission_test.go
- api/internal/lesson/validation/teacher_shift.go
- api/internal/lesson/validation/teacher_shift_test.go
- api/internal/lesson/validation/validator.go
- api/mock/lesson/database/database.go
- api/mock/lesson/validation/validator.go
- api/mock/proto/lesson/service_grpc.pb.go.go
- api/proto/lesson/service.proto
> feat(lesson-api): implement list teacher submissions

- .github/workflows/cd-api-classroom-for-main.yaml
- .github/workflows/cd-api-user-for-main.yaml
- .github/workflows/cd-gateway-teacher-for-main.yaml
- .github/workflows/ci-backend-for-all.yaml
https://github.com/calmato/shs-web/issues/36 の対応
> fix(ci): add emulator ping timeout

- .github/workflows/cd-api-lesson-for-main.yaml
> feat(ci): setup lesson api workflow

- api/hack/database-seeds/main.go
database-seedsコマンドを実行したときdefaultですべて再作成にしていたのをupsertだけに変更しました
> feat(hack): chanding default value

- api/internal/lesson/api/teacher_shift.go
- api/internal/lesson/api/teacher_shift_test.go
- api/internal/lesson/database/database.go
- api/internal/lesson/database/teacher_shift.go
- api/internal/lesson/database/teacher_shift_test.go
- api/internal/lesson/database/teacher_submission.go
- api/internal/lesson/database/teacher_submission_test.go
- api/internal/lesson/validation/teacher_shift.go
- api/internal/lesson/validation/teacher_shift_test.go
- api/internal/lesson/validation/validator.go
- api/mock/lesson/database/database.go
- api/mock/lesson/validation/validator.go
- api/mock/proto/lesson/service_grpc.pb.go.go
- api/proto/lesson/service.proto
> feat(lesson-api): implement list teacher shifts

- api/internal/gateway/teacher/v1/handler/api.go
- api/internal/gateway/teacher/v1/handler/teacher_shift.go
- api/internal/gateway/teacher/v1/handler/teacher_shift_test.go
- docs/swagger/teacher/paths/v1/teachers/_teacherId/submissions/_summaryId.yaml
> feat(gateway): implement list teacher shifts api

- api/internal/lesson/api/teacher_shift.go
- api/internal/lesson/api/teacher_shift_test.go
- api/internal/lesson/entity/shift_summary.go
シフト提出前の状態だとうまくレスポンスが取得できなかったので修正しました
> fix(lesson-api): add check shift submission

- api/internal/lesson/api/teacher_shift.go
シフト提出前の状態だとうまくレスポンスが取得できなかったので修正しました
> fix(lesson-api): fix error handling

- api/internal/user/database/database.go
- api/internal/user/database/student.go
- api/internal/user/database/student_test.go
- api/mock/user/database/database.go
createStudentのinterfaceと詳細を追加
usecase層の実装
> feat(user-api): createStudent database layer

- api/config/classroom/server/config.go
- api/internal/classroom/api/teacher_subject.go
- api/internal/classroom/api/teacher_subject_test.go
- api/internal/classroom/cmd/server/exec.go
- api/internal/classroom/cmd/server/registry.go
- docker-compose.yaml
渡すcontextを間違えていた影響でgoroutineの停止命令がうまく伝播できずnil pointerになっている箇所があったので修正しました。
> fix(classroom-api): fix goroutine in upsert subjects

- web/teacher/src/components/templates/MbShiftTop.vue
- web/teacher/src/components/templates/TheSubmissionTop.vue
- web/teacher/src/layouts/error.vue
デスクトップ表示時、画像サイズが大きすぎると画面からはみ出してしまっていたのでmax-heightの設定をしました
> fix(web/teacher): fix image size in desktop layout

- .github/workflows/cd-web-student-for-main.yaml
> feat(ci/cd): setup deploy student web

- api/internal/classroom/api/api_test.go
- api/internal/classroom/api/student_subject.go
- api/internal/classroom/api/student_subject_test.go
- api/internal/classroom/validation/student_subject.go
- api/internal/classroom/validation/student_subject_test.go
- api/internal/classroom/validation/validator.go
- api/mock/classroom/validation/validator.go
> Feat/classroom api/implement student subject api

- api/internal/user/api/teacher.go
- api/internal/user/api/teacher_test.go
- api/internal/user/database/database.go
- api/internal/user/database/teacher.go
- api/internal/user/database/teacher_test.go
- api/internal/user/validation/teacher.go
- api/internal/user/validation/teacher_test.go
- api/internal/user/validation/validator.go
- api/mock/proto/user/service_grpc.pb.go.go
- api/mock/user/database/database.go
- api/mock/user/validation/validator.go
- api/proto/user/service.proto
> feat(user-api): implement delete teacher api

- api/hack/database-seeds/main.go
- api/internal/user/api/teacher.go
- api/internal/user/api/teacher_test.go
- api/internal/user/database/database.go
- api/internal/user/database/teacher.go
- api/internal/user/database/teacher_test.go
- api/internal/user/entity/teacher.go
- api/internal/user/entity/teacher_test.go
- api/internal/user/validation/teacher.go
- api/internal/user/validation/teacher_test.go
- api/internal/user/validation/validator.go
- api/mock/proto/user/service_grpc.pb.go.go
- api/mock/user/database/database.go
- api/mock/user/validation/validator.go
- api/proto/user/service.proto
> feat(user-api): implement update teacher role api

- api/internal/gateway/teacher/v1/entity/schedule.go
- api/internal/gateway/teacher/v1/entity/schedule_test.go
- api/internal/gateway/teacher/v1/handler/schedule_test.go
- docs/swagger/teacher/components/schemas/v1/schedules.request.yaml
> feat(gateway): changing update schedules request

- api/internal/gateway/teacher/v1/handler/api.go
- api/internal/gateway/teacher/v1/handler/auth.go
- api/internal/gateway/teacher/v1/handler/auth_test.go
- api/internal/gateway/teacher/v1/handler/subject.go
- api/internal/gateway/teacher/v1/handler/subject_test.go
- api/internal/gateway/teacher/v1/handler/teacher.go
- api/internal/gateway/teacher/v1/handler/teacher_test.go
- api/internal/gateway/teacher/v1/request/auth.go
- api/internal/gateway/teacher/v1/request/subject.go
- api/internal/gateway/teacher/v1/request/teacher.go
- api/internal/gateway/teacher/v1/response/teacher.go
- docs/swagger/teacher/components/schemas/v1/auth.response.yaml
- docs/swagger/teacher/components/schemas/v1/teachers.request.yaml
- docs/swagger/teacher/components/schemas/v1/teachers.response.yaml
- docs/swagger/teacher/openapi.yaml
- docs/swagger/teacher/paths/v1/teachers/_teacherId/subjects.yaml
> feat(gateway): implement update teacher subjects api

- web/teacher/src/components/atoms/TheSelectWithSlot.vue
- web/teacher/src/components/organisms/TheTeacherEditCard.vue
- web/teacher/src/components/organisms/TheTeacherList.vue
- web/teacher/src/components/organisms/TheTeacherShowCard.vue
- web/teacher/src/components/templates/TheUserTop.vue
- web/teacher/src/pages/index.vue
- web/teacher/src/pages/settings/index.vue
- web/teacher/src/pages/users/index.vue
- web/teacher/src/store/lesson.ts
- web/teacher/src/store/user.ts
- web/teacher/src/types/api/v1/index.ts
- web/teacher/src/types/api/v1/lesson.ts
- web/teacher/src/types/api/v1/user.ts
- web/teacher/src/types/form/lesson.ts
- web/teacher/src/types/form/teacher.ts
- web/teacher/src/types/store/lesson.ts
- web/teacher/src/types/store/user.ts
- web/teacher/test/components/atoms/TheSelectWithSlot.test.ts
- web/teacher/test/components/organisms/TheTeacherEditCard.test.ts
- web/teacher/test/components/organisms/TheTeacherList.test.ts
- web/teacher/test/components/templates/TheUserTop.test.ts
- web/teacher/test/helpers/api-mock/index.ts
- web/teacher/test/helpers/api-mock/lesson.ts
- web/teacher/test/helpers/api-mock/user.ts
- web/teacher/test/helpers/store-helper.ts
- web/teacher/test/store/lesson.test.ts
- web/teacher/test/store/user.test.ts
講師の詳細ダイアログの実装をしました。
テストコードなしで差分がかなりあるため、別PRにてテストコードの作成をしたいと思います。
* roleに応じた表示の変更
> feat(web/teacher): implement show teacher dialog

- web/teacher/src/components/atoms/TheSelect.vue
- web/teacher/src/components/atoms/TheSelectWithSlot.vue
- web/teacher/src/components/organisms/TheTeacherEditCard.vue
- web/teacher/src/components/templates/TheUserTop.vue
- web/teacher/src/layouts/default.vue
- web/teacher/src/pages/users/index.vue
- web/teacher/src/store/auth.ts
- web/teacher/src/types/props/menu.ts
- web/teacher/test/components/organisms/TheMenu.test.ts
- web/teacher/test/components/organisms/TheSidebar.test.ts
- web/teacher/test/components/organisms/TheTeacherEditCard.test.ts
- web/teacher/test/components/templates/TheUserTop.test.ts
- web/teacher/test/store/auth.test.ts
> feat(web/teacher): swith ui by role

- api/internal/gateway/teacher/v1/handler/api.go
403返すところでnil pointerとなりパニックが起きてたので修正しました
> fix(gateway): fix nil pointer for error handling

- web/teacher/src/components/organisms/TheTeacherEditCard.vue
- web/teacher/src/components/templates/TheUserTop.vue
- web/teacher/src/pages/users/index.vue
- web/teacher/src/store/user.ts
- web/teacher/test/components/organisms/TheTeacherEditCard.test.ts
- web/teacher/test/components/templates/TheUserTop.test.ts
- web/teacher/test/helpers/api-mock/index.ts
- web/teacher/test/helpers/api-mock/user.ts
- web/teacher/test/store/user.test.ts
https://github.com/calmato/shs-web/pull/166 の続き
講師削除ボタンを実装しました
> Feat/teacher web/delete teacher

- api/mock/proto/user/service_grpc.pb.go.go
- api/proto/user/service.proto
ListStudents用のproto定義を追加
データベース層
> feat(user-api): add ListStudents proto

- web/teacher/src/store/lesson.ts
- web/teacher/test/store/lesson.test.ts
デグレの影響で動かなくなっていた箇所 (講師編集ダイアログで科目一覧が取得できない) を修正しました
> fix(web/teacher): fix edit teacher dialog

- api/internal/lesson/api/api_test.go
- api/internal/lesson/api/student_shift.go
- api/internal/lesson/api/student_shift_test.go
- api/internal/lesson/database/database.go
- api/internal/lesson/database/student_shift.go
- api/internal/lesson/database/student_shift_test.go
- api/internal/lesson/database/student_submission.go
- api/internal/lesson/database/student_submission_test.go
- api/internal/lesson/validation/student_shift.go
- api/internal/lesson/validation/student_shift_test.go
- api/internal/lesson/validation/validator.go
- api/mock/lesson/database/database.go
- api/mock/lesson/validation/validator.go
- api/mock/proto/lesson/service_grpc.pb.go.go
- api/proto/lesson/service.proto
生徒の授業希望関連APIの実装をしました
(講師側実装の100%コピペなので、一気に実装しちゃってます)
> feat(lesson-api): implement student submissions

- api/internal/lesson/api/student_shift.go
- api/internal/lesson/api/student_shift_test.go
- api/internal/lesson/database/database.go
- api/internal/lesson/database/student_submission.go
- api/internal/lesson/database/student_submission_test.go
- api/internal/lesson/validation/student_shift.go
- api/internal/lesson/validation/student_shift_test.go
- api/internal/lesson/validation/validator.go
- api/mock/lesson/database/database.go
- api/mock/lesson/validation/validator.go
- api/mock/proto/lesson/service_grpc.pb.go.go
- api/proto/lesson/service.proto
> feat(lesson-api): implement list student submissions api

- api/internal/gateway/entity/student.go
- api/internal/gateway/entity/student_shift.go
- api/internal/gateway/entity/student_shift_test.go
- api/internal/gateway/entity/student_submission.go
- api/internal/gateway/entity/student_submission_test.go
- api/internal/gateway/entity/teacher_test.go
- api/internal/gateway/teacher/v1/entity/student.go
- api/internal/gateway/teacher/v1/entity/student_submission.go
- api/internal/gateway/teacher/v1/entity/student_submission_test.go
- api/internal/gateway/teacher/v1/entity/student_test.go
- api/internal/gateway/teacher/v1/entity/subject.go
- api/internal/gateway/teacher/v1/entity/subject_test.go
- api/internal/gateway/teacher/v1/handler/shift.go
- api/internal/gateway/teacher/v1/handler/shift_test.go
- api/internal/gateway/teacher/v1/response/shift.go
- docs/swagger/teacher/components/schemas/v1/shifts.response.yaml
> feat(gateway): update list shifts api response

- api/internal/user/api/student.go
- api/internal/user/api/student_test.go
- api/internal/user/database/database.go
- api/internal/user/database/student.go
- api/internal/user/database/student_test.go
- api/internal/user/validation/student.go
- api/internal/user/validation/student_test.go
- api/internal/user/validation/validator.go
- api/mock/proto/user/service_grpc.pb.go.go
- api/mock/user/database/database.go
- api/mock/user/validation/validator.go
- api/proto/user/service.proto
ListStudentsのusecase層の実装
update系ordelete系
> feat(user-api): ListStudents usecase layer

- api/internal/lesson/database/database.go
- api/internal/lesson/database/lesson.go
- api/internal/lesson/database/lesson_test.go
- api/internal/lesson/entity/lesson.go
- api/mock/lesson/database/database.go
- infra/mysql/schema/2022011601-lessons-create-table-lessons.sql
> feat(lesson-api): define lesson entity

- api/internal/gateway/teacher/v1/handler/shift.go
- api/internal/gateway/teacher/v1/handler/shift_test.go
変更前のListStudentRequestにしてしまっていたものが使われて
mainブランチでエラーになっていたので
変更後のListStudentsRequestに統一
> fix:translate ListStudentRequest

- api/internal/lesson/database/lesson_test.go
テストコード内で、並列実行にするとうまく動かない箇所があったので修正しました
> fix(lesson-api): fix test code in lesson db

- api/mock/proto/user/service_grpc.pb.go.go
- api/proto/user/service.proto
DeleteStudentのproto定義
database, usecase層
> feat(user-api): add DeleteStudent Proto

- api/internal/classroom/api/room.go
- api/internal/classroom/api/room_test.go
- api/internal/classroom/database/database.go
- api/internal/classroom/database/room.go
- api/internal/classroom/database/room_test.go
- api/internal/classroom/entity/room.go
- api/internal/classroom/entity/room_test.go
- api/internal/classroom/validation/room.go
- api/internal/classroom/validation/room_test.go
- api/internal/classroom/validation/validator.go
- api/mock/classroom/database/database.go
- api/mock/classroom/validation/validator.go
- api/mock/proto/classroom/service_grpc.pb.go.go
- api/proto/classroom/room.proto
- api/proto/classroom/service.proto
> feat(classroom-api): implement get room api

- api/internal/lesson/api/api_test.go
- api/internal/lesson/api/lesson.go
- api/internal/lesson/api/lesson_test.go
- api/internal/lesson/database/database.go
- api/internal/lesson/database/lesson_test.go
- api/internal/lesson/database/shift.go
- api/internal/lesson/database/shift_test.go
- api/internal/lesson/entity/lesson.go
- api/internal/lesson/entity/lesson_test.go
- api/internal/lesson/validation/lesson.go
- api/internal/lesson/validation/lesson_test.go
- api/internal/lesson/validation/validator.go
- api/mock/lesson/database/database.go
- api/mock/lesson/validation/validator.go
- api/mock/proto/lesson/service_grpc.pb.go.go
- api/proto/lesson/lesson.proto
- api/proto/lesson/service.proto
> feat(lesson-api): implement create lesson api

- api/internal/lesson/api/lesson.go
- api/internal/lesson/api/lesson_test.go
- api/internal/lesson/entity/lesson.go
- api/internal/lesson/entity/lesson_test.go
- api/internal/lesson/validation/lesson.go
- api/internal/lesson/validation/lesson_test.go
- api/internal/lesson/validation/validator.go
- api/mock/lesson/validation/validator.go
- api/mock/proto/lesson/service_grpc.pb.go.go
- api/proto/lesson/service.proto
> feat(lesson-api): implement list lessons api

- api/internal/lesson/api/lesson.go
- api/internal/lesson/api/lesson_test.go
- api/proto/lesson/service.proto
> feat(lesson-api): update create lesson api response

- api/internal/gateway/teacher/v1/handler/api.go
- api/internal/gateway/teacher/v1/handler/lesson.go
- api/internal/gateway/teacher/v1/handler/lesson_test.go
- api/internal/gateway/teacher/v1/request/lesson.go
- api/internal/gateway/teacher/v1/response/lesson.go
- docs/swagger/teacher/components/schemas/v1/lessons.request.yaml
- docs/swagger/teacher/components/schemas/v1/lessons.response.yaml
- docs/swagger/teacher/openapi.yaml
- docs/swagger/teacher/paths/v1/shifts/_shiftId/lessons/index.yaml
> feat(gateway): implement create lesson api

- web/teacher/src/components/organisms/TheShiftLessonCard.vue
- web/teacher/src/components/templates/MbShiftDetail.vue
- web/teacher/src/components/templates/PcShiftDetail.vue
- web/teacher/src/pages/shifts/_id.vue
授業登録画面のUIを微調整しました。このPR以降で少しずつAPIとの連携を進めていく予定です。
* テストコードの作成
* API連携
* 各項目クリック時の動作の実装
> feat(web/teacher): implement create lesson page design

- api/internal/gateway/entity/lesson.go
- api/internal/gateway/entity/lesson_test.go
- api/internal/gateway/teacher/v1/entity/student_submission.go
- api/internal/gateway/teacher/v1/entity/student_submission_test.go
- api/internal/gateway/teacher/v1/entity/teacher_submission.go
- api/internal/gateway/teacher/v1/entity/teacher_submission_test.go
- api/internal/gateway/teacher/v1/handler/shift.go
- api/internal/gateway/teacher/v1/handler/shift_test.go
> fix(gateway): fix lesson total fields

- web/teacher/src/components/organisms/TheShiftLessonList.vue
- web/teacher/src/components/organisms/TheShiftStudentTable.vue
- web/teacher/src/components/organisms/TheShiftTeacherTable.vue
- web/teacher/src/components/templates/PcShiftDetail.vue
授業作成画面について、わかりにくかったので適度にコンポーネント分割しました
> fix(web/teacher): split components in create lessons page

- api/internal/gateway/teacher/v1/entity/student_shift.go
- api/internal/gateway/teacher/v1/entity/student_shift_test.go
- api/internal/gateway/teacher/v1/entity/student_submission.go
- api/internal/gateway/teacher/v1/entity/student_submission_test.go
- api/internal/gateway/teacher/v1/handler/api.go
- api/internal/gateway/teacher/v1/handler/student_shift.go
- api/internal/gateway/teacher/v1/handler/student_shift_test.go
- api/internal/gateway/teacher/v1/response/submission.go
- docs/swagger/teacher/components/schemas/v1/shifts.response.yaml
- docs/swagger/teacher/openapi.yaml
- docs/swagger/teacher/paths/v1/shifts/_shiftId/students/_studentId.yaml
> feat(gateway): implement list enabled student shifts api

- api/internal/user/api/student.go
- api/internal/user/api/student_test.go
- api/internal/user/validation/student.go
- api/internal/user/validation/student_test.go
- api/internal/user/validation/validator.go
- api/mock/user/validation/validator.go
> feat(user-api): add DeleteStudent usecase layer

- api/internal/gateway/entity/subject.go
- api/internal/gateway/entity/subject_test.go
- api/internal/gateway/teacher/v1/entity/student_submission_test.go
- api/internal/gateway/teacher/v1/entity/teacher.go
- api/internal/gateway/teacher/v1/entity/teacher_submission.go
- api/internal/gateway/teacher/v1/entity/teacher_submission_test.go
- api/internal/gateway/teacher/v1/entity/teacher_test.go
- api/internal/gateway/teacher/v1/handler/shift.go
- api/internal/gateway/teacher/v1/handler/shift_test.go
- api/internal/gateway/teacher/v1/handler/subject.go
- api/internal/gateway/teacher/v1/handler/teacher.go
- api/internal/gateway/teacher/v1/handler/teacher_test.go
- api/internal/gateway/teacher/v1/response/teacher.go
- docs/swagger/teacher/components/schemas/v1/shifts.response.yaml
- docs/swagger/teacher/components/schemas/v1/teachers.response.yaml
> fix(gateway): fix teacher response

- api/internal/gateway/entity/student_subject.go
- api/internal/gateway/entity/student_subject_test.go
- api/internal/gateway/entity/subject.go
- api/internal/gateway/entity/subject_test.go
- api/internal/gateway/teacher/v1/entity/student.go
- api/internal/gateway/teacher/v1/entity/student_submission.go
- api/internal/gateway/teacher/v1/entity/student_submission_test.go
- api/internal/gateway/teacher/v1/entity/student_test.go
- api/internal/gateway/teacher/v1/handler/shift.go
- api/internal/gateway/teacher/v1/handler/shift_test.go
- api/internal/gateway/teacher/v1/handler/subject.go
- docs/swagger/teacher/components/schemas/v1/shifts.response.yaml
> feat(gateway): update student response

- Makefile
- startだとコンテナそのものが存在しないまっさらな状態だと失敗してしまうのでupに修正
なし
なし
> fix: migrate task

- web/teacher/src/pages/settings/index.vue
- web/teacher/src/pages/settings/mail.vue
- web/teacher/src/types/form/teacher.ts
> Add: Added update mail page

- api/internal/user/api/teacher.go
- api/internal/user/api/teacher_test.go
- api/internal/user/database/database.go
- api/internal/user/database/teacher.go
- api/internal/user/database/teacher_test.go
- api/internal/user/validation/teacher.go
- api/internal/user/validation/teacher_test.go
- api/internal/user/validation/validator.go
- api/mock/proto/user/service_grpc.pb.go.go
- api/mock/user/database/database.go
- api/mock/user/validation/validator.go
- api/proto/user/service.proto
> feat(user-api): implement multi get teachers

- web/teacher/src/components/templates/TheClassroomSetting.vue
- web/teacher/src/components/templates/TheSettingTop.vue
- web/teacher/src/layouts/default.vue
- web/teacher/src/pages/settings/classroom.vue
- web/teacher/src/pages/settings/index.vue
- 設定画面の背景色が違う問題に対応
- 「定休日/コマ/ブース 設定」画面でブース設定を一番上にした
- 戻るボタンを「定休日/コマ/ブース 設定」画面に移動
> 設定画面のUIを調整

- web/teacher/src/pages/settings/mail.vue
> Refactor: にしくんの苦情を修正

- docker-compose.yaml
- docs/swagger/student/openapi.yaml
- docs/swagger/teacher/components/schemas/v1/students.response.yaml
- docs/swagger/teacher/openapi.yaml
- docs/swagger/teacher/paths/v1/students/_studentId/index.yaml
GetStudentのindex作成
responseの型定義
make start-swaggerで生成されるファイルの場所を修正
> feat(gateway): define GetStudent API specification

- api/internal/lesson/api/shift.go
- api/internal/lesson/api/shift_test.go
- api/internal/lesson/database/database.go
- api/internal/lesson/database/lesson.go
- api/internal/lesson/database/shift.go
- api/internal/lesson/database/shift_test.go
- api/internal/lesson/validation/shift_test.go
- api/mock/lesson/database/database.go
- api/proto/lesson/service.proto
シフト一覧取得APIで、ShiftIdでも値が取得できるように改修しました
> feat(lesson-api): update list shifts api request

- api/internal/gateway/teacher/v1/handler/shift.go
- api/internal/gateway/teacher/v1/handler/shift_test.go
- api/internal/gateway/teacher/v1/handler/student.go
- api/internal/gateway/teacher/v1/handler/teacher.go
授業スケジュール毎の情報取得APIのTODOになっていた箇所を実装しました
> feat(gateway): implement list submissions api

- web/teacher/src/pages/settings/index.vue
- web/teacher/src/pages/settings/password.vue
- web/teacher/src/types/form/teacher.ts
Password変更ページの実装
APIとのつなぎを実装する
> Add: added update password page

- api/internal/lesson/api/student_shift.go
- api/internal/lesson/api/teacher_shift.go
シフト提出状況取得APIで、NotFoundのときヌルポで落ちる箇所があったので修正しました
> fix(lesson-api): fix null pointer in get subumission api

- api/internal/gateway/teacher/v1/entity/lesson.go
- api/internal/gateway/teacher/v1/handler/api.go
- api/internal/gateway/teacher/v1/handler/lesson.go
- api/internal/gateway/teacher/v1/handler/lesson_test.go
- api/internal/gateway/teacher/v1/response/lesson.go
- api/internal/lesson/api/lesson.go
- api/internal/lesson/api/lesson_test.go
- api/internal/lesson/database/database.go
- api/internal/lesson/database/lesson.go
- api/internal/lesson/entity/lesson.go
- api/mock/lesson/database/database.go
- api/proto/lesson/service.proto
- docs/swagger/teacher/components/schemas/v1/lessons.response.yaml
- docs/swagger/teacher/openapi.yaml
- docs/swagger/teacher/paths/v1/shifts/_shiftId/lessons/index.yaml
> Feat/lesson api/list lessons api

- api/internal/gateway/teacher/v1/handler/api.go
- api/internal/gateway/teacher/v1/handler/student.go
- api/internal/gateway/teacher/v1/handler/student_test.go
- api/internal/gateway/teacher/v1/response/student.go
- docs/swagger/teacher/components/schemas/v1/students.response.yaml
- docs/swagger/teacher/openapi.yaml
- docs/swagger/teacher/paths/v1/students/index.yaml
ListStudentsの仕様作成
handlerの作成
Proto -> Entity の処理
> feat(gateway): add ListStudents mock

- api/internal/gateway/teacher/v1/entity/student_submission.go
- api/internal/gateway/teacher/v1/entity/student_submission_test.go
- api/internal/gateway/teacher/v1/handler/shift_test.go
- docs/swagger/teacher/components/schemas/v1/shifts.response.yaml
- web/teacher/src/components/organisms/TheShiftLessonNewCard.vue
- web/teacher/src/components/organisms/TheShiftStudentSubmissionCard.vue
- web/teacher/src/components/organisms/TheShiftTeacherSubmissionCard.vue
- web/teacher/src/components/templates/PcShiftDetail.vue
- web/teacher/src/pages/shifts/_id.vue
- web/teacher/src/store/shift.ts
- web/teacher/src/types/form/shift.ts
- web/teacher/src/types/props/shift.ts
- web/teacher/src/types/props/user.ts
- web/teacher/src/types/store/shift.ts
> Feat/teacher web/implement new lessons

- web/teacher/src/components/organisms/TheShiftLessonNewCard.vue
- web/teacher/src/components/organisms/TheShiftNewCard.vue
- web/teacher/src/components/templates/PcShiftDetail.vue
- web/teacher/src/pages/shifts/_id.vue
- web/teacher/src/store/shift.ts
- web/teacher/src/types/api/v1/shift.ts
- web/teacher/src/types/form/shift.ts
授業登録ダイアログとAPIクライアントの実装をしました
* 授業更新APIの実装
* 授業削除APIの実装
* 授業スケジュール確定APIの実装
> feat(web/teacher): implement new lessons dialog design

- web/teacher/src/components/organisms/TheShiftStudentLessonCard.vue
- web/teacher/src/components/organisms/TheShiftTeacherLessonCard.vue
- web/teacher/src/components/organisms/TheShiftTeacherSubmissionCard.vue
- web/teacher/src/components/templates/PcShiftDetail.vue
- web/teacher/src/pages/shifts/_id.vue
- web/teacher/src/store/shift.ts
- web/teacher/src/types/props/shift.ts
- web/teacher/src/types/store/shift.ts
登録された授業の一覧を確認するためのダイアログを実装しました
> feat(web/teacher): implement list lessons per user dialog

- api/internal/lesson/api/lesson.go
- api/internal/lesson/api/lesson_test.go
- api/internal/lesson/validation/lesson.go
- api/internal/lesson/validation/lesson_test.go
- api/internal/lesson/validation/validator.go
- api/mock/lesson/validation/validator.go
- api/mock/proto/lesson/service_grpc.pb.go.go
- api/proto/lesson/service.proto
> feat(lesson-api): implement update lesson api

- api/internal/gateway/teacher/v1/handler/api.go
- api/internal/gateway/teacher/v1/handler/lesson.go
- api/internal/gateway/teacher/v1/handler/lesson_test.go
- api/internal/gateway/teacher/v1/request/lesson.go
- docs/swagger/teacher/components/schemas/v1/lessons.request.yaml
- docs/swagger/teacher/openapi.yaml
- docs/swagger/teacher/paths/v1/shifts/_shiftId/lessons/_lessonId.yaml
> feat(gateway): implement update lesson api

- api/internal/lesson/api/lesson.go
- api/internal/lesson/api/lesson_test.go
- api/internal/lesson/validation/lesson.go
- api/internal/lesson/validation/lesson_test.go
- api/internal/lesson/validation/validator.go
- api/mock/lesson/validation/validator.go
- api/mock/proto/lesson/service_grpc.pb.go.go
- api/proto/lesson/service.proto
> feat(lesson-api): implement delete lesson api

- api/internal/gateway/teacher/v1/handler/api.go
- api/internal/gateway/teacher/v1/handler/student.go
- api/internal/gateway/teacher/v1/handler/student_test.go
- docs/swagger/teacher/paths/v1/students/_studentId/index.yaml
> feat(Gateway): add DeleteStudent mock

- api/internal/gateway/teacher/v1/handler/api.go
- api/internal/gateway/teacher/v1/handler/lesson.go
- api/internal/gateway/teacher/v1/handler/lesson_test.go
- docs/swagger/teacher/paths/v1/shifts/_shiftId/lessons/_lessonId.yaml
> feat(gateway): implement delete lesson api

- api/internal/gateway/entity/shift_summary_test.go
- api/internal/gateway/teacher/v1/entity/shift_summary.go
- api/internal/gateway/teacher/v1/entity/shift_summary_test.go
- docs/swagger/teacher/components/schemas/v1/shifts.response.yaml
授業スケジュール確定を管理するためのフィールドを追加しました。
> feat(gateway): add fields lesson decided

- api/internal/lesson/api/shift.go
- api/internal/lesson/api/shift_test.go
- api/internal/lesson/database/database.go
- api/internal/lesson/database/shift_summary.go
- api/internal/lesson/database/shift_summary_test.go
- api/internal/lesson/validation/shift.go
- api/internal/lesson/validation/shift_test.go
- api/internal/lesson/validation/validator.go
- api/mock/lesson/database/database.go
- api/mock/lesson/validation/validator.go
- api/mock/proto/lesson/service_grpc.pb.go.go
- api/proto/lesson/service.proto
> feat(lesson-api): implement update shift decided api

- api/internal/gateway/teacher/v1/handler/api.go
- api/internal/gateway/teacher/v1/handler/shift.go
- api/internal/gateway/teacher/v1/handler/shift_test.go
- api/internal/gateway/teacher/v1/request/shift.go
- docs/swagger/teacher/components/schemas/v1/shifts.request.yaml
- docs/swagger/teacher/openapi.yaml
- docs/swagger/teacher/paths/v1/shifts/_shiftId/decided.yaml
> feat(gateway): implement udpate shift decided api

- web/teacher/src/pages/settings/mail.vue
- web/teacher/src/store/user.ts
- web/teacher/src/types/api/v1/user.ts
- web/teacher/src/types/form/teacher.ts
passwordのupdateのAPIとの繋ぎを実装
update完了した時にどこか違うページにするべきだったか？
> Add: added update mail API by BFF

- api/internal/gateway/teacher/v1/handler/lesson_test.go
- api/internal/lesson/api/lesson.go
- api/internal/lesson/api/lesson_test.go
- web/teacher/src/components/templates/TheTop.vue
- web/teacher/src/pages/index.vue
- web/teacher/src/store/lesson.ts
- web/teacher/src/store/shift.ts
- web/teacher/src/types/api/v1/lesson.ts
- web/teacher/src/types/api/v1/shift.ts
- web/teacher/src/types/store/lesson.ts
- web/teacher/test/components/templates/TheTop.test.ts
- web/teacher/test/store/lesson.test.ts
> feat(web/teacher): implement list lessons api client

- web/teacher/src/components/organisms/TheShiftEditCard.vue
- web/teacher/src/components/organisms/TheShiftNewCard.vue
- web/teacher/src/components/organisms/TheShiftTopCard.vue
- web/teacher/src/components/organisms/TheTeacherEditCard.vue
- web/teacher/src/components/templates/PcShiftTop.vue
> refactor(web/teacher): dialog button

- web/teacher/src/components/organisms/TheShiftEditCard.vue
- web/teacher/src/components/organisms/TheShiftStudentTable.vue
- web/teacher/src/components/organisms/TheShiftTeacherTable.vue
テーブルにカーソルを当てたとき、ポインタの表示が変わるように修正しました
> refactor(web/teacher): refactor table style

- api/internal/user/api/student.go
- api/internal/user/api/student_test.go
- api/internal/user/database/database.go
- api/internal/user/database/student.go
- api/internal/user/validation/student.go
- api/internal/user/validation/student_test.go
- api/internal/user/validation/validator.go
- api/mock/proto/user/service_grpc.pb.go.go
- api/mock/user/database/database.go
- api/mock/user/validation/validator.go
- api/proto/user/service.proto
> feat(user-api): implement update student api

- web/teacher/src/components/organisms/TheBoothSettingForm.vue
- web/teacher/src/components/organisms/TheCalendarDetail.vue
- web/teacher/src/components/organisms/TheCalendarHeader.vue
- web/teacher/src/components/organisms/TheShiftEditCard.vue
- web/teacher/src/components/organisms/TheShiftLessonNewCard.vue
- web/teacher/src/components/organisms/TheShiftNewCard.vue
- web/teacher/src/components/organisms/TheShiftStudentLessonCard.vue
- web/teacher/src/components/organisms/TheShiftStudentSubmissionCard.vue
- web/teacher/src/components/organisms/TheShiftTeacherLessonCard.vue
- web/teacher/src/components/organisms/TheShiftTeacherSubmissionCard.vue
- web/teacher/src/components/organisms/TheShiftTopCard.vue
- web/teacher/src/components/organisms/TheSubmissionList.vue
- web/teacher/src/components/organisms/TheTeacherEditCard.vue
- web/teacher/src/components/templates/PcShiftDetail.vue
- web/teacher/src/components/templates/PcShiftTop.vue
- web/teacher/src/components/templates/TheClassroomSetting.vue
- web/teacher/src/components/templates/TheSubmissionTop.vue
- web/teacher/src/components/templates/TheTeacherNew.vue
- web/teacher/src/components/templates/TheUserTop.vue
- web/teacher/src/pages/settings/classroom.vue
- web/teacher/src/pages/settings/index.vue
- web/teacher/src/pages/settings/subjects.vue
- web/teacher/test/components/templates/TheSubmissionTop.test.ts
> fix: デザインレビュー会で話した内容を反映

- api/internal/gateway/teacher/v1/handler/api.go
- api/internal/gateway/teacher/v1/handler/student.go
- api/internal/gateway/teacher/v1/handler/student_test.go
- api/internal/gateway/teacher/v1/request/student.go
- docs/swagger/teacher/components/schemas/v1/students.request.yaml
- docs/swagger/teacher/openapi.yaml
- docs/swagger/teacher/paths/v1/students/_studentId/mail.yaml
- docs/swagger/teacher/paths/v1/students/_studentId/password.yaml
> feat(gateway): implement update student api

- api/internal/gateway/student/v1/entity/auth.go
- api/internal/gateway/student/v1/entity/auth_test.go
- api/internal/gateway/student/v1/entity/subject.go
- api/internal/gateway/student/v1/entity/subject_test.go
- api/internal/gateway/student/v1/handler/api.go
- api/internal/gateway/student/v1/handler/auth.go
- api/internal/gateway/student/v1/handler/auth_test.go
- api/internal/gateway/student/v1/request/auth.go
- api/internal/gateway/student/v1/response/auth.go
- docs/swagger/student/components/schemas/v1/auth.request.yaml
- docs/swagger/student/components/schemas/v1/auth.response.yaml
- docs/swagger/student/openapi.yaml
- docs/swagger/student/paths/v1/me/mail.yaml
- docs/swagger/student/paths/v1/me/password.yaml
- docs/swagger/teacher/components/schemas/v1/students.request.yaml
- docs/swagger/teacher/openapi.yaml
> feat(gateway): implement auth api

- api/internal/gateway/student/v1/entity/shift_summary.go
- api/internal/gateway/student/v1/entity/shift_summary_test.go
- api/internal/gateway/student/v1/entity/student.go
- api/internal/gateway/student/v1/entity/student_shift.go
- api/internal/gateway/student/v1/entity/student_shift_test.go
- api/internal/gateway/student/v1/entity/student_submission.go
- api/internal/gateway/student/v1/entity/student_submission_test.go
- api/internal/gateway/student/v1/entity/student_test.go
- api/internal/gateway/student/v1/handler/api.go
- api/internal/gateway/student/v1/handler/submission.go
- api/internal/gateway/student/v1/handler/submission_test.go
- api/internal/gateway/student/v1/request/submission.go
- api/internal/gateway/student/v1/response/submission.go
- docs/swagger/student/components/schemas/v1/submissions.request.yaml
- docs/swagger/student/components/schemas/v1/submissions.response.yaml
- docs/swagger/student/openapi.yaml
- docs/swagger/student/paths/v1/submissions/_summaryId.yaml
- docs/swagger/student/paths/v1/submissions/index.yaml
授業希望提出関連APIの実装をしました (まとめて実装したため差分多くなってます)
> feat(gateway): implement submission api

- api/internal/gateway/student/v1/handler/api.go
- api/internal/gateway/student/v1/handler/subject.go
- api/internal/gateway/student/v1/handler/subject_test.go
- api/internal/gateway/student/v1/response/subject.go
- docs/swagger/student/components/schemas/v1/subjects.response.yaml
- docs/swagger/student/openapi.yaml
- docs/swagger/student/paths/v1/subjects/index.yaml
> feat(gateway): implement subjects api

- web/teacher/src/lib/convert.ts
- web/teacher/src/store/shift.ts
> refactor(web/teacher): refactor shift store code

- api/internal/gateway/entity/student_shift_template.go
- api/internal/gateway/entity/student_shift_template_test.go
- api/internal/gateway/entity/student_submission.go
- api/internal/gateway/entity/student_submission_test.go
- api/internal/gateway/student/v1/entity/studeht_shift_template_test.go
- api/internal/gateway/student/v1/entity/student_shift.go
- api/internal/gateway/student/v1/entity/student_shift_template.go
- api/internal/gateway/student/v1/entity/student_shift_test.go
- api/internal/gateway/student/v1/entity/student_submission.go
- api/internal/gateway/student/v1/entity/student_submission_test.go
- api/internal/gateway/student/v1/handler/api.go
- api/internal/gateway/student/v1/handler/submission.go
- api/internal/gateway/student/v1/handler/submission_test.go
- api/internal/gateway/student/v1/request/submission.go
- api/internal/gateway/student/v1/response/submission.go
- api/internal/gateway/teacher/v1/entity/student_submission.go
- api/internal/gateway/teacher/v1/entity/student_submission_test.go
- api/internal/gateway/teacher/v1/handler/student_shift.go
- api/internal/lesson/api/student_shift_test.go
- api/internal/lesson/entity/student_shift_template.go
- api/internal/lesson/entity/student_shift_template_test.go
- api/proto/lesson/student_shift.proto
- docs/swagger/student/components/schemas/v1/submissions.request.yaml
- docs/swagger/student/components/schemas/v1/submissions.response.yaml
- docs/swagger/student/openapi.yaml
- docs/swagger/student/paths/v1/me/submission.yaml
> feat(gateway): implement submission template api

- api/internal/gateway/student/v1/entity/student.go
- api/internal/gateway/student/v1/entity/subject.go
- api/internal/gateway/student/v1/entity/subject_test.go
- api/internal/gateway/student/v1/handler/auth.go
- api/internal/gateway/teacher/v1/entity/student.go
- api/internal/gateway/teacher/v1/entity/subject.go
- api/internal/gateway/teacher/v1/entity/subject_test.go
- docs/swagger/teacher/components/schemas/v1/students.response.yaml
校種(SchoolType)でフィルターをかけていた生徒の授業科目一覧レスポンスについて、フィルターをせずすべて返すように修正しました
> fix(gateway): remove filter subjects

- api/internal/classroom/database/schedule.go
スケジュール更新APIについて、クエリ周りの不具合を修正しました
> fix(classroom-api): fix multiple update schedule

- web/teacher/src/components/templates/TheClassroomSetting.vue
- web/teacher/src/pages/settings/classroom.vue
- web/teacher/src/store/classroom.ts
- web/teacher/src/types/api/v1/classroom.ts
- web/teacher/src/types/store/classroom.ts
- web/teacher/test/store/classroom.test.ts
- 定休日/コマ/ブース 設定の編集機能の実装
最下部に「保存」ボタンを追加してそこから更新する形にした。
> feat: 定休日/コマ/ブース 設定の編集機能の実装

- web/teacher/src/pages/settings/subjects.vue
- 開講科目設定画面に遷移した際にでていたコンソールエラーの修正
> fix: gが抜けていたので修正

- web/teacher/src/components/organisms/TheCalendarBody.vue
- web/teacher/src/components/organisms/TheShiftLessonCard.vue
- web/teacher/src/components/organisms/TheShiftLessonNewCard.vue
- web/teacher/src/components/organisms/TheShiftStudentLessonCard.vue
- web/teacher/src/components/organisms/TheShiftStudentSubmissionCard.vue
- web/teacher/src/components/organisms/TheShiftTeacherLessonCard.vue
- web/teacher/src/lib/convert.ts
- web/teacher/src/pages/index.vue
- web/teacher/src/types/store/lesson.ts
- web/teacher/test/components/organisms/TheTeacherEditCard.test.ts
- web/teacher/test/components/templates/TheUserTop.test.ts
- web/teacher/test/store/auth.test.ts
- web/teacher/test/store/lesson.test.ts
- web/teacher/test/store/user.test.ts
講師Webアプリでの科目名の表示を `${校種(SchoolType)}${科目名(Name}}` の形式で表示されるように修正しました。
> feat(web/teacher): add subject name field

- api/internal/gateway/teacher/v1/handler/api.go
- api/internal/gateway/teacher/v1/handler/student.go
- api/internal/gateway/teacher/v1/handler/student_test.go
- api/internal/gateway/teacher/v1/request/student.go
- docs/swagger/teacher/components/schemas/v1/students.request.yaml
生徒の受講科目について、今の校種に関わらず更新できるようにしました
> fix(gateway): fix update student subjects

- web/teacher/src/components/organisms/TheStudentEditCard.vue
- web/teacher/src/components/organisms/TheStudentList.vue
- web/teacher/src/components/templates/TheUserTop.vue
- web/teacher/src/pages/users/index.vue
- web/teacher/src/store/user.ts
- web/teacher/src/types/api/v1/user.ts
- web/teacher/src/types/form/student.ts
- web/teacher/src/types/store/user.ts
- web/teacher/test/store/user.test.ts
生徒更新/削除周りのAPIリクエストを投げるためのAPIクライアント実装をしました。
> feat(web/teacher): implement api client for update student

- web/teacher/src/components/organisms/TheShiftStudentLessonCard.vue
- web/teacher/src/components/organisms/TheShiftStudentSubmissionCard.vue
- web/teacher/src/components/organisms/TheShiftTeacherLessonCard.vue
- web/teacher/src/components/organisms/TheShiftTeacherSubmissionCard.vue
- web/teacher/src/components/templates/PcShiftDetail.vue
- web/teacher/src/pages/shifts/_id.vue
* closes: https://github.com/calmato/shs-web/issues/279
> refactor(web/teacher): refactor shift dialog

- web/teacher/src/pages/settings/mail.vue
- web/teacher/src/pages/settings/password.vue
- web/teacher/src/store/auth.ts
- web/teacher/src/store/user.ts
- web/teacher/src/types/api/v1/auth.ts
メールアドレス, パスワード変更後、API認証に使用するTokenを破棄するための処理を追加しました。
> fix(web/teacher): fix update auth page

- Makefile
API実装を進めていくのに併せてMakefileを更新すべきだったけど忘れてました...
なので、このタイミングで起動周りのコマンドを修正しました。
> chore(*): udpate start container commands

- .github/workflows/cd-api-classroom-for-main.yaml
- .github/workflows/cd-api-gateway-for-main.yaml
- .github/workflows/cd-api-lesson-for-main.yaml
- .github/workflows/cd-api-messenger-for-main.yaml
- .github/workflows/cd-api-user-for-main.yaml
- infra/docker/api/messenger/notifier/Dockerfile
- infra/docker/api/messenger/server/Dockerfile
- infra/kubernetes/.gitignore
- infra/kubernetes/Makefile
- infra/kubernetes/stg/default/classroom-api.deployment.yaml.temp
- infra/kubernetes/stg/default/classroom-api.secret.yaml.temp
- infra/kubernetes/stg/default/classroom-api.service.yaml
- infra/kubernetes/stg/default/common.ingress.yaml
- infra/kubernetes/stg/default/common.secret.yaml.temp
- infra/kubernetes/stg/default/lesson-api.deployment.yaml.temp
- infra/kubernetes/stg/default/lesson-api.secret.yaml.temp
- infra/kubernetes/stg/default/lesson-api.service.yaml
- infra/kubernetes/stg/default/messenger-api.deployment.yaml.temp
- infra/kubernetes/stg/default/messenger-api.secret.yaml.temp
- infra/kubernetes/stg/default/messenger-api.service.yaml
- infra/kubernetes/stg/default/messenger-notifier.deployment.yaml.temp
- infra/kubernetes/stg/default/messenger-notifier.secret.yaml.temp
- infra/kubernetes/stg/default/student-gateway.deployment.yaml.temp
- infra/kubernetes/stg/default/student-gateway.service.yaml
- infra/kubernetes/stg/default/teacher-gateway.deployment.yaml.temp
- infra/kubernetes/stg/default/teacher-gateway.service.yaml
- infra/kubernetes/stg/default/user-api.deployment.yaml.temp
- infra/kubernetes/stg/default/user-api.secret.yaml.temp
- infra/kubernetes/stg/default/user-api.service.yaml
クラウド環境での検証用にK8sのマニフェストを作成しました。(余裕あったらhelm使った書き方に変えたい...)
> feat(kubernetes): setup kubernetes manifests

- api/config/classroom/server/config.go
- api/config/gateway/student/config.go
- api/config/gateway/teacher/config.go
- api/config/lesson/server/config.go
- api/config/user/server/config.go
- api/internal/classroom/cmd/server/exec.go
- api/internal/lesson/cmd/server/exec.go
- api/internal/user/cmd/server/exec.go
CloudSQLでTimeZone指定が対応していなかったため、実行時に環境変数から指定できるようにしました
> feat(api): update execute config

- api/config/user/server/config.go
- api/internal/user/cmd/server/exec.go
- api/internal/user/cmd/server/registy.go
- infra/kubernetes/stg/default/classroom-api.deployment.yaml.temp
- infra/kubernetes/stg/default/common.secret.yaml.temp
- infra/kubernetes/stg/default/lesson-api.deployment.yaml.temp
- infra/kubernetes/stg/default/user-api.deployment.yaml.temp
> fix(kubernetes): fix api config

- web/student/nuxt.config.js
- web/student/src/components/templates/TheSubmissionTop.vue
- web/student/src/pages/submissions/index.vue
- web/student/src/plugins/store-accessor.ts
- web/student/src/store/submission.ts
- web/student/src/types/api/v1/index.ts
- web/student/src/types/api/v1/submission.ts
- web/student/src/types/store/common.ts
- web/student/src/types/store/index.ts
- web/student/src/types/store/submission.ts
- web/teacher/nuxt.config.js
> Add: added student submission list page

- web/student/src/pages/settings/mail.vue
- web/student/src/store/auth.ts
- web/student/src/types/api/v1/auth.ts
- web/student/src/types/form/student.ts
> Add: added setting update mail page

- api/pkg/log/logger.go
> feat(api): update logger config

- web/teacher/src/components/organisms/TheHourSettingForm.vue
- web/teacher/src/components/organisms/TheShiftLessonList.vue
> Fix: fixed layout

- infra/kubernetes/stg/default/common.ingress.yaml
K8sのIngress周りのマニフェストを修正しました。
(Teacher側とStudent側でドメインを分割しました)
> fix(infra): fix k8s manifests for ingress

- api/internal/gateway/student/v1/entity/subject.go
- api/internal/gateway/student/v1/entity/subject_test.go
- api/internal/gateway/teacher/v1/entity/subject.go
- api/internal/gateway/teacher/v1/entity/subject_test.go
科目一覧のレスポンスについて、カラーコード (生徒側は校種も) でソートして返すようにしました
> feat(gateway): subjects sort by color code

- web/student/.eslintrc.js
- web/student/src/components/organisms/TheCalendarBody.vue
- web/student/src/components/organisms/TheCalendarDetail.vue
- web/student/src/components/organisms/TheCalendarHeader.vue
- web/student/src/components/templates/TheTop.vue
- web/student/src/lib/convert.ts
- web/student/src/lib/index.ts
- web/student/src/pages/index.vue
- web/student/src/plugins/store-accessor.ts
- web/student/src/store/auth.ts
- web/student/src/store/lesson.ts
- web/student/src/types/api/v1/auth.ts
- web/student/src/types/api/v1/index.ts
- web/student/src/types/api/v1/lesson.ts
- web/student/src/types/props/calendar.ts
- web/student/src/types/store/auth.ts
- web/student/src/types/store/common.ts
- web/student/src/types/store/index.ts
- web/student/src/types/store/lesson.ts
- web/student/test/helpers/api-mock/auth.ts
- web/student/test/store/auth.test.ts
> feat(web/student): implement top page

- api/internal/gateway/student/v1/handler/lesson.go
- api/internal/gateway/student/v1/handler/lesson_test.go
生徒側のGatewayにて、授業一覧取得APIに投げるリクエスト値が誤っていたので修正しました
> fix(gateway): fix list lessons api

- web/student/src/pages/settings/class.vue
> feat: 生徒側の授業希望のカスタム設定画面のUIを作成

- web/teacher/src/middleware/authenticated.ts
- web/teacher/src/store/common.ts
- web/teacher/src/types/store/common.ts
- web/teacher/test/store/common.test.ts
画面遷移のたびに実行されている処理があるため、初回だけ実行されるように修正しました。
> fix(web/teacher): eliminate duplicate processing

- api/internal/gateway/student/v1/handler/submission.go
- web/student/src/components/molecules/TheSettingUserFormItem.vue
- web/student/src/components/organisms/TheSubmissionScheduleList.vue
- web/student/src/components/organisms/TheSubmissionShiftList.vue
- web/student/src/components/templates/TheSettingClass.vue
- web/student/src/components/templates/TheSettingTop.vue
- web/student/src/layouts/default.vue
- web/student/src/pages/settings/class.vue
- web/student/src/pages/settings/index.vue
- web/student/src/plugins/dayjs.ts
- web/student/src/store/submission.ts
- web/student/src/types/api/v1/submission.ts
- web/student/src/types/store/submission.ts
> feat(web/student): implement custom schedule page

- infra/mysql/schema/2022021401-lessons-alter-column-to-shifts.sql
ライブラリとクラウドサービスの仕様の兼ね合いで、DATE型で定義している箇所をDATETIME型へ変更しました
> feat(mysql): alter column to shifts

- web/teacher/src/components/organisms/TheRegularHolidaySettingForm.vue
- web/teacher/src/components/templates/TheClassroomSetting.vue
- web/teacher/src/middleware/authenticated.ts
- web/teacher/src/pages/settings/classroom.vue
- web/teacher/src/store/classroom.ts
* closes: https://github.com/calmato/shs-web/issues/310
> fix(web/teacher): fix edit schedule logic

- web/student/src/middleware/authenticated.ts
- web/student/src/store/common.ts
- web/student/src/types/store/common.ts
生徒側のMiddleware実装を講師側の実装に併せて修正しました
> feat(web/student): update middleware logic

- web/student/src/components/organisms/TheHeader.vue
- web/student/src/layouts/auth.vue
- web/teacher/src/components/organisms/TheHeader.vue
- web/teacher/src/layouts/auth.vue
サインイン画面にハンバーガーメニューが出てしまっているのを修正しました
* closes: https://github.com/calmato/shs-web/issues/322
> fix(web): hidden hamburger menu in signin

- web/teacher/src/pages/settings/subjects.vue
> feat: 「閉じる」ボタンの追加

- web/teacher/src/components/organisms/TheShiftStudentSubmissionCard.vue
- web/teacher/src/store/shift.ts
- web/teacher/src/types/store/shift.ts
生徒の授業希望一覧確認ダイアログへ、授業の残り登録必要数を表示させるようにしました
* closes: https://github.com/calmato/shs-web/issues/319
> feat(web/teacher): add remaining total in student submission
