calmato/shs-web

- api/internal/gateway/cmd/teacher/router.go
- api/internal/gateway/teacher/v1/entity/auth.go
- api/internal/gateway/teacher/v1/handler/api.go
- api/internal/gateway/teacher/v1/handler/api_test.go
- api/internal/gateway/teacher/v1/handler/auth.go
- api/internal/gateway/teacher/v1/handler/auth_test.go
- api/internal/gateway/teacher/v1/handler/teacher.go
- api/internal/gateway/teacher/v1/handler/teacher_test.go
- api/internal/gateway/teacher/v1/response/auth.go
- api/internal/gateway/util/metadata.go
- api/internal/gateway/util/metadata_test.go
講師認証情報取得APIのモック作成
* https://github.com/calmato/shs-web/pull/18 のマージ後に詳細実装
> feat(gateway): add get auth api mock

- web/teacher/src/layouts/default.vue
- スマホレイアウトにした際に右側に余白ができる問題への対応
多分あんまり良い対応策ではない…
どうやってもHeader要素が可変になってしまったので泣く泣くこうした
> feat: スマホレイアウトにした際に右側に余白ができる問題への対応

- web/teacher/src/components/organisms/TheStudentList.vue
- web/teacher/src/pages/users/index.vue
- web/teacher/src/store/user.ts
- web/teacher/src/types/api/v1/user.ts
- web/teacher/src/types/store/common.ts
- web/teacher/test/components/organisms/TheStudentList.test.ts
- web/teacher/test/helpers/api-mock/index.ts
- web/teacher/test/helpers/api-mock/user.ts
- web/teacher/test/store/user.test.ts
講師一覧APIから取得した情報をテーブルに表示できるように設定
* UIの調整
* Limit, Offset指定で一覧情報を取得できるように
* 検索フォームの追加対応
> feat(web/teacher): implement list teacher api client

- api/internal/gateway/teacher/v1/handler/teacher.go
- api/internal/gateway/teacher/v1/handler/teacher_test.go
- api/internal/gateway/teacher/v1/response/teacher.go
- api/internal/user/api/teacher.go
- api/internal/user/api/teacher_test.go
- api/internal/user/database/database.go
- api/internal/user/database/teacher.go
- api/internal/user/database/teacher_test.go
- api/mock/user/database/database.go
- api/proto/user/service.proto
- docs/swagger/teacher/components/schemas/v1/teachers.response.yaml
講師一覧取得APIのレスポンスへ、DBに保存されているレコードの数を返す用のフィールドを追加しました。
> feat(user-api): add total field in list teachers response

- web/teacher/src/store/auth.ts
- web/teacher/src/store/lesson.ts
- web/teacher/src/types/api/v1/auth.ts
- web/teacher/src/types/store/auth.ts
- web/teacher/src/types/store/lesson.ts
- web/teacher/test/helpers/api-mock/auth.ts
- web/teacher/test/store/auth.test.ts
- web/teacher/test/store/lesson.test.ts
ログインユーザー情報取得APIから受け取るレスポンスのフィールド定義を追加
> feat(web/teacher): add auth response field

- api/internal/gateway/teacher/v1/handler/api.go
- api/internal/gateway/teacher/v1/handler/auth.go
- api/internal/gateway/teacher/v1/handler/auth_test.go
- api/internal/gateway/teacher/v1/request/auth.go
- docs/swagger/teacher/components/schemas/v1/auth.request.yaml
- docs/swagger/teacher/openapi.yaml
- docs/swagger/teacher/paths/v1/me/mail.yaml
- docs/swagger/teacher/paths/v1/me/password.yaml
メールアドレスの更新APIとパスワードの更新APIをそれぞれ実装しました
> feat(gateway): implement update email and password api

- api/internal/lesson/api/api_test.go
- api/internal/lesson/api/shift.go
- api/internal/lesson/api/shift_test.go
- api/internal/lesson/database/database.go
- api/internal/lesson/database/shift_summary.go
- api/internal/lesson/database/shift_summary_test.go
- api/internal/lesson/entity/shift_summary.go
- api/internal/lesson/entity/shift_summary_test.go
- api/internal/lesson/validation/shift.go
- api/internal/lesson/validation/shift_test.go
- api/internal/lesson/validation/validator.go
- api/mock/lesson/database/database.go
- api/mock/lesson/validation/validator.go
- api/mock/proto/lesson/service_grpc.pb.go.go
- api/proto/lesson/service.proto
> feat(lesson-api): implement list shift summaries api

- Makefile
`make migrate` コマンド実行時、gRPC周りの更新も同時に行うようにMakefileを変更しました。
`make proto` を一番はじめに実行する書き方にしてもよかったんですが、mysqlサービスへのping実行が成功したあとも起動処理が続いてその後の処理が失敗することがあったので、pingコマンド実行後に `make proto` を実行して時間をかせぐようにしています
> fix(infra): update makefile

- api/internal/classroom/api/api.go
- api/internal/classroom/api/api_test.go
- api/internal/classroom/database/database.go
- api/internal/lesson/api/api.go
- api/internal/lesson/api/api_test.go
- api/internal/lesson/database/database.go
- api/internal/user/database/database.go
データがすでに存在するときのエラーハンドリングができていなかったため、409 (Conflict) のステータスが変えるような実装を追加しました
* closes https://github.com/calmato/shs-web/issues/72
> fix(*): add error handling when record already exists at create

- api/internal/lesson/api/shift.go
- api/internal/lesson/api/shift_test.go
- api/internal/lesson/database/database.go
- api/internal/lesson/database/shift_summary.go
- api/internal/lesson/database/shift_summary_test.go
- api/internal/lesson/validation/shift.go
- api/internal/lesson/validation/shift_test.go
- api/internal/lesson/validation/validator.go
- api/mock/lesson/database/database.go
- api/mock/lesson/validation/validator.go
- api/mock/proto/lesson/service_grpc.pb.go.go
- api/proto/lesson/service.proto
> feat(lesson-api): implement update shift summary schedule

- api/internal/lesson/api/shift.go
シフト募集の登録後、募集ステータスの代入ができていなくUNKNOWNでレスポンスが返ってきてしまっていたため修正しました
> fix(lesson-api): fix fill status after shift created

- api/internal/classroom/api/api.go
- api/internal/classroom/api/api_test.go
- api/internal/lesson/api/api.go
- api/internal/lesson/api/api_test.go
- api/internal/user/api/api.go
- api/internal/user/api/api_test.go
> feat(api): add grpc error handling

- api/pkg/jst/jst.go
- api/pkg/jst/jst_test.go
time.Time形式の引数を渡すことで年度を返してくれるメソッドを追加しました
> feat(api): add return fiscal year method

- web/teacher/src/components/organisms/TheHeader.vue
- web/teacher/src/components/organisms/TheSidebar.vue
- web/teacher/src/layouts/default.vue
- web/teacher/test/components/organisms/TheSidebar.test.ts
> feat(web/teacher): implement desktop default layout

- api/mock/proto/classroom/service_grpc.pb.go.go
- api/proto/classroom/service.proto
- api/proto/classroom/student_subject.proto
- infra/mysql/schema/2022010401-classrooms-create-table-student-subjects.sql
生徒の受講教科管理用APIの実装にあたり、まずはprotoの定義をしました
> feat(classroom-api): define student subjects proto

- api/internal/classroom/database/database.go
- api/internal/classroom/database/student_subject.go
- api/internal/classroom/database/student_subject_test.go
- api/internal/classroom/entity/student_subject.go
- api/internal/classroom/entity/student_subject_test.go
- api/mock/classroom/database/database.go
生徒の受講科目管理テーブルの操作インターフェースを実装しました
> feat(classroom-api): implement student subjects db logic

- api/internal/gateway/entity/teacher.go
- api/internal/gateway/entity/teacher_shift.go
- api/internal/gateway/teacher/v1/entity/teacher_submission.go
- api/internal/gateway/teacher/v1/entity/teacher_submission_test.go
- api/internal/gateway/teacher/v1/handler/shift.go
- api/internal/gateway/teacher/v1/handler/shift_test.go
- api/internal/gateway/teacher/v1/handler/teacher_shift.go
- api/internal/gateway/teacher/v1/handler/teacher_shift_test.go
- api/internal/gateway/teacher/v1/response/shift.go
- api/internal/lesson/api/teacher_shift.go
- api/internal/lesson/api/teacher_shift_test.go
- api/internal/lesson/database/database.go
- api/internal/lesson/database/teacher_shift.go
- api/internal/lesson/database/teacher_shift_test.go
- api/internal/lesson/validation/teacher_shift.go
- api/internal/lesson/validation/teacher_shift_test.go
- api/internal/lesson/validation/validator.go
- api/mock/lesson/database/database.go
- api/mock/lesson/validation/validator.go
- api/mock/proto/lesson/service_grpc.pb.go.go
- api/proto/lesson/service.proto
- docs/swagger/teacher/components/schemas/v1/shifts.response.yaml
シフト詳細APIのレスポンスへ講師関連情報の追加
* 生徒側の詳細が決まり次第、レスポンスも追加
> feat(gateway): add fields to shifts response

- web/teacher/src/components/molecules/TheSubjectSelectFormItem.vue
- web/teacher/src/components/templates/TheSettingTop.vue
- web/teacher/src/pages/settings/index.vue
- APIリクエストの数を減らすためににも教科を変更するイベント検知を`change`から`blur`に変更
特になし。
特になし。
> fix: 教科変更のイベント検知をchangeメソッドからblurメソッドに変更

- api/internal/user/database/database.go
- api/internal/user/database/student.go
- api/internal/user/database/student_test.go
- api/mock/user/database/database.go
> add databese  layer

- web/teacher/src/pages/settings/classroom.vue
- web/teacher/src/pages/settings/index.vue
- コマ/ブース設定画面のUIだけ作成
- パスの設定がわからなかったので`settings/classroom`にした。
- コンポーネント化
- ロジックなど
- APIとの接続
> feat(web/teacher): コマ/ブース設定画面のUIだけ作成

- api/internal/lesson/entity/student_shift.go
- api/internal/lesson/entity/student_shift_test.go
- api/internal/lesson/entity/student_submission.go
- api/internal/lesson/entity/student_submission_test.go
- api/proto/lesson/student_shift.proto
- api/proto/lesson/student_submission.proto
- infra/mysql/schema/2022011401-lessons-create-table-student-shifts.sql
生徒の授業希望を管理するためのDDLを作成しました。
授業希望なので `student_lessons` とかの命名のほうが適切かと考えたのですが、先につくっている講師のシフト希望 `teacher_shifts` と併せたほうがわかりやすいので、テーブル名は `student_shifts` にしてます。
> feat(lesson-api): define student submissions entity

- api/internal/lesson/api/student_shift.go
- api/internal/lesson/api/student_shift_test.go
- api/internal/lesson/database/student_submission.go
- api/internal/lesson/database/student_submission_test.go
- api/internal/lesson/entity/student_submission.go
- api/internal/lesson/entity/student_submission_test.go
- api/proto/lesson/service.proto
- api/proto/lesson/student_submission.proto
- infra/mysql/schema/2022011501-lessons-add-column-to-student-submissions.sql
生徒の授業希望管理テーブルへ希望授業回数を管理するためのカラムを追加しました
> feat(lesson-api): add field to student submission entity

- api/internal/user/database/database.go
- api/internal/user/database/student.go
- api/internal/user/database/student_test.go
- api/mock/user/database/database.go
interfaceにDeleteStudentを追加
メソッドの詳細、テスト
usecase層
> feat(user-api): add DeleteStudent database layer

- web/teacher/src/components/organisms/TheShiftEditCard.vue
- web/teacher/src/components/organisms/TheShiftNewCard.vue
シフト作成ダイアログにて、 `h4` タグの付与箇所が誤っていたので修正しました。
併せて、期間指定の入力フォームのUIの微調整 ( `~` の位置を中央寄せ) にする修正もしています。
> fix(web/teacher): fix create shift dialog

- api/internal/lesson/api/lesson.go
- api/internal/lesson/api/lesson_test.go
- api/internal/lesson/database/database.go
- api/internal/lesson/database/lesson.go
- api/internal/lesson/database/lesson_test.go
- api/internal/lesson/validation/lesson.go
- api/internal/lesson/validation/lesson_test.go
- api/internal/lesson/validation/validator.go
- api/mock/lesson/validation/validator.go
- api/mock/proto/lesson/service_grpc.pb.go.go
- api/proto/lesson/service.proto
講師ID, 生徒IDベースで授業一覧を取得するためのAPIを実装しました
> feat(lesson-api): implement list lessons api

- api/internal/lesson/api/shift.go
- api/internal/lesson/api/shift_test.go
- api/internal/lesson/database/database.go
- api/internal/lesson/database/student_shift.go
- api/internal/lesson/database/student_shift_test.go
- api/internal/lesson/database/teacher_shift.go
- api/internal/lesson/database/teacher_shift_test.go
- api/internal/lesson/validation/shift.go
- api/internal/lesson/validation/shift_test.go
- api/internal/lesson/validation/validator.go
- api/mock/lesson/database/database.go
- api/mock/lesson/validation/validator.go
- api/mock/proto/lesson/service_grpc.pb.go.go
- api/proto/lesson/service.proto
ShiftIdごとの出勤可能講師, 受講希望生徒それぞれの一覧取得用APIを実装しました。
> Feat/lesson api/implement list submissions

- api/internal/gateway/entity/student_shift.go
- api/internal/gateway/entity/student_shift_test.go
- api/internal/gateway/entity/teacher_shift.go
- api/internal/gateway/entity/teacher_shift_test.go
- api/internal/gateway/teacher/v1/handler/api.go
- api/internal/gateway/teacher/v1/handler/shift.go
- api/internal/gateway/teacher/v1/handler/shift_test.go
- api/internal/gateway/teacher/v1/handler/student.go
- api/internal/gateway/teacher/v1/handler/teacher.go
- api/internal/gateway/teacher/v1/response/shift.go
- docs/swagger/teacher/components/schemas/v1/shifts.response.yaml
- docs/swagger/teacher/openapi.yaml
- docs/swagger/teacher/paths/v1/shifts/_shiftId/submissions/_submissionId.yaml
シフトIDに対する勤務可能講師, 授業希望生徒の一覧をそれぞれ取得するAPIを実装しました
> feat(gateway): implement list submissions api

- api/internal/gateway/teacher/v1/entity/student_submission.go
- api/internal/gateway/teacher/v1/entity/student_submission_test.go
- api/internal/gateway/teacher/v1/handler/student_shift.go
- api/internal/gateway/teacher/v1/handler/student_shift_test.go
- api/internal/gateway/teacher/v1/response/submission.go
- docs/swagger/teacher/components/schemas/v1/shifts.response.yaml
生徒の受講希望一覧取得APIで科目毎の受講希望回数も返すようにしました。
> feat(gateway): add response field to get student shift api

- api/internal/classroom/api/subject.go
- api/internal/classroom/api/subject_test.go
授業科目登録APIにて、レスポンスの詰め忘れがあってnilポインターが起こっていた箇所を修正しました
> fix(classroom-api): fix create subject response

- web/teacher/src/pages/shifts/_id.vue
授業登録画面の初期描画が遅いので、まずは仮のローディング画面出すようにしました
このあとスケルトンローダーに置き換えられたらしたいとおもいます
> feat(web/teacher): add loader in shift detail page

- api/internal/lesson/api/lesson.go
- api/internal/lesson/api/lesson_test.go
- api/internal/lesson/database/database.go
- api/internal/lesson/database/shift_summary.go
- api/internal/lesson/database/shift_summary_test.go
- api/internal/lesson/entity/lesson.go
- api/internal/lesson/entity/lesson_test.go
- api/internal/lesson/entity/shift_summary.go
- api/internal/lesson/entity/shift_summary_test.go
- api/internal/lesson/validation/lesson_test.go
- api/mock/lesson/database/database.go
- api/proto/lesson/service.proto
- api/proto/lesson/shift_summary.proto
- infra/mysql/schema/2022013001-lessons-aadd-column-to-shift-summaries.sql
授業スケジュール確定有無を管理するためのフィールドを追加しました
> feat(lesson-api): add field to shift summary entity

- api/internal/lesson/api/api_test.go
- api/internal/lesson/api/student_shift.go
- api/internal/lesson/api/student_shift_test.go
- api/internal/lesson/database/database.go
- api/internal/lesson/database/student_shift_template.go
- api/internal/lesson/database/student_shift_template_test.go
- api/internal/lesson/entity/student_shift_template.go
- api/internal/lesson/entity/student_shift_template_test.go
- api/internal/lesson/validation/student_shift.go
- api/internal/lesson/validation/student_shift_test.go
- api/internal/lesson/validation/validator.go
- api/mock/lesson/database/database.go
- api/mock/lesson/validation/validator.go
- api/mock/proto/lesson/service_grpc.pb.go.go
- api/proto/lesson/service.proto
- api/proto/lesson/student_shift.proto
- api/proto/lesson/student_submission.proto
- infra/mysql/schema/2022020201-lessons-create-table-student-shift-templates.sql
生徒の希望授業テンプレート管理用のAPIを実装しました
(Classroom Service側に寄せても良いかもと迷ったんだけど、Lesson関連との関係性のほうが強そうなのでLesson Serviceへ寄せました)
> feat(lesson-api): implement student shift template api

- web/teacher/src/components/organisms/TheShiftLessonCard.vue
シフト登録ページのレイアウトについて、ノートPCサイズの画面で見ると改行の位置が微妙な感じになっているため、レイアウトの微修正をしました。
> fix(web/teacher): fix lesson list layout

- api/internal/lesson/api/shift.go
- api/internal/lesson/api/shift_test.go
現状だと、シフト作成画面で `授業を修正する` のボタンを押してもメール通知が飛んでしまっていました。
そのため、 `授業を確定する` のボタンを押したときのみメール通知が飛ぶように修正しました。
> fix(lesson-api): fix notify lesson decided

- api/internal/gateway/student/v1/entity/lesson.go
- api/internal/gateway/student/v1/entity/lesson_test.go
- api/internal/gateway/teacher/v1/entity/lesson.go
- api/internal/gateway/teacher/v1/entity/lesson_test.go
授業一覧ダイアログでの表示について、授業日時順で並んでほしいところがバラバラな順番で表示されてしまっていました。
そのため、レスポンスを授業開始日時順でソートできるよう修正しました。。
> fix(gateway): lessons sort by start at

- api/internal/messenger/cmd/notifier/exec.go
- api/internal/messenger/notifier/notifier.go
- api/internal/messenger/notifier/notifier_test.go
- api/pkg/pubsub/puller_test.go
- infra/kubernetes/stg/default/messenger-notifier.deployment.yaml.temp
一定時間したらPodが停止処理に入ってしまう不具合について、不要なヘルスチェックが設定されていたためであったため修正しました。(ついでにテストカバレッジの向上, 不要なコードの削除周りもしました)
> fix(messenger-api): fix health check timeout

- api/internal/gateway/entity/teacher_submission.go
- api/internal/gateway/entity/teacher_submission_test.go
- api/internal/gateway/teacher/v1/entity/student_submission.go
- api/internal/gateway/teacher/v1/entity/student_submission_test.go
- api/internal/gateway/teacher/v1/entity/teacher_submission.go
- api/internal/gateway/teacher/v1/entity/teacher_submission_test.go
- api/internal/gateway/teacher/v1/handler/shift.go
- api/internal/gateway/teacher/v1/handler/shift_test.go
- docs/swagger/teacher/components/schemas/v1/shifts.response.yaml
クライアント実装も並行して進められるように、まずはAPIのレスポンスへシフト/授業希望提出フラグを追加しました。
* https://github.com/calmato/shs-web/issues/317
> feat(gateway): add field to list shifts response

- api/internal/lesson/api/teacher_shift.go
- api/internal/lesson/api/teacher_shift_test.go
- api/internal/lesson/database/database.go
- api/internal/lesson/database/teacher_submission.go
- api/internal/lesson/database/teacher_submission_test.go
- api/internal/lesson/validation/teacher_shift.go
- api/internal/lesson/validation/teacher_shift_test.go
- api/internal/lesson/validation/validator.go
- api/mock/lesson/database/database.go
- api/mock/lesson/validation/validator.go
- api/mock/proto/lesson/service_grpc.pb.go.go
- api/proto/lesson/service.proto
講師ID一覧をもとに提出されたシフト一覧を取得するAPIを実装しました。
* https://github.com/calmato/shs-web/issues/317
> feat(lesson-api): implement list teacher submissions by teacher ids

- web/student/src/components/organisms/TheHeader.vue
- web/student/src/components/organisms/TheMenu.vue
- web/student/src/layouts/default.vue
- web/teacher/src/components/organisms/TheHeader.vue
- web/teacher/src/components/organisms/TheMenu.vue
- web/teacher/src/layouts/default.vue
- メニューがずれないようにした。
* closes: https://github.com/calmato/shs-web/issues/321
> fix: メニューの表示がずれないように修正
